### ISSUE TITLE
Adding support for disk consolidation needed.

### ISSUE THREAD

**Issue by takenek** [dnaeon/py-vpoller#103]
Hello
This is possible to add trigger to vpoller for disk consolidation?
Now when i got information in vCenter about disk need consolidation in zabbix there is no info....

Thanks

**Comment by dnaeon** [comment]
Zabbix support for vSphere alarms is present in the latest vPoller release.

Make sure to get the latest vPoller templates for Zabbix as well.

The example items in the ``Template VMware vSphere Datacenter - vPoller Native`` template contains discovery items, which would discover all triggered alarms in a Datacenter.

**Comment by sirmaxru** [comment]
Hello. 
What is about alarms from vCenter. 
I cant get how to recieve alarms from it. for example "vCenter Server Health Alarm"?
