### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#104]
Hi Marin
I have started to get some performance issues with Zabbix/ Vpoller.
The current proxy server has 2185 hosts and 24124 items, mostly made up servers using vpoller.

The queue is not large but there is items waiting, currently the 5 minute queue is 3606, but more than 10 minutes is only 25.  So the queries are eventually being processed, but not in a timely manner.  

The vpoller worker config is running 18  processes and the server has 12 CPU's, with avg cpu load per core of 0.85.

Any ideas ?

Thanks,
Bradley

**Comment by dnaeon** [comment]
Bradley,

The latest releases of vPoller and vConnector come with caching of vSphere managed objects, which should fixed these performance issues.

Could you please upgrade to the latest vConnector 0.3.5 and vPoller 0.3.9-dev release and see how they perform?

Thanks,
Marin
