### ISSUE TITLE
vpoller monitor for monitoring vmware datastore

### ISSUE THREAD

**Issue by tnndlbmu** [dnaeon/py-vpoller#105]
Hi Marin,
the datastore discoveried by py-vpoller, and the visible name shows "ds:///vmfs/volumes/e3e651d4-ab1f9f64/" see the screenshot, it's hard to catch the datastore issue if happend because the visible name is hard to read and distinguish which datastores have issue.
![datastore](https://cloud.githubusercontent.com/assets/8831381/4975762/880cbaf4-6917-11e4-86db-b964749880c5.jpg)
so i changed the visible name and hostname in template "Template VMware vSphere - vPoller Native" see the screenshot,
![template](https://cloud.githubusercontent.com/assets/8831381/4976033/98481136-691a-11e4-95b2-aa2e5a82b346.jpg)
and then it's easy to know which datastore's. but the issue happen, the monitoring data from py-vpoller for datastores are stopped, and check the discovery status see the error ,screenshot,
![error](https://cloud.githubusercontent.com/assets/8831381/4976630/9f059582-6921-11e4-8456-471933818bb5.jpg)
kindly pls help, thanks.

**Comment by olfway** [comment]
May be instead of putting "ds:///vmfs/volumes/4e5e7de4-ebcdf133-d078-001b78976fc0/" in hostname
(which is prohibited by zabbix's name check)
it can be stored as "ds_4e5e7de4-ebcdf133-d078-001b78976fc0"
and original url could be also stored as host-level macro or host description?

what do you think?

**Comment by dnaeon** [comment]
Yep, that could be possible. Unfortunately I don't have enough spare time to get this going, so if anyone wants to pick this up, I'd be glad to get some pull requests.

**Comment by sirmaxru** [comment]
is there any possibility to convert ds:///vmfs/volumes/4e5e7de4-ebcdf133-d078-001b78976fc0/
to 4e5e7de4-ebcdf133-d078-001b78976fc0 ?

**Comment by dnaeon** [comment]
Closing this one as I don't have enough bandwidth to work on it. If anyone is willing to pick this up, please feel free to do so.
