### ISSUE TITLE
Information about datastore performance parameters ?

### ISSUE THREAD

**Issue by oitss** [dnaeon/py-vpoller#110]
Is it possible to add method to query vim.StorageResourceManager.StoragePerformanceSummary for getting information about datastore performance parameters ?

**Comment by dnaeon** [comment]
Performance counters are now available in vPoller starting with release 0.3.9.

Documentation on how to use performance counters with vPoller can be found in the link below:

 - http://vpoller.readthedocs.org/en/latest/examples.html#performance-metrics

The Zabbix templates for vPoller will be updated soon with some examples on how to use performance counters with vPoller and Zabbix as well.
