### ISSUE TITLE
vPoller: Discover VMware Virtual Machines - can not detect VM

### ISSUE THREAD

**Issue by georg1ch** [dnaeon/py-vpoller#117]
Hi,
"Template VMware vSphere - vPoller: Discover VMware Virtual Machines" can not detect VM
In this case, all other rights of detection (Clusters, Datacenters, Datastores, Hypervisors) work out perfectly.
The logs do not find errors.
Commando run from the console: vpoller-client --method vm.discover --vsphere-host vc01
All VM detected
Can someone faced with this would be very grateful for any help.
pyvmomi==5.5.0.2014.1.1
requests==2.5.1
vconnector==0.3.1
vpoller==0.3.5
Zabbix 2.4.3

p.s. sorry for my english

best regards,
Sergey

**Comment by dnaeon** [comment]
Hey Sergey,

Are you running vPoller with the loadable Zabbix module for vPoller or using the externalscripts?

Thanks,
Marin

**Comment by georg1ch** [comment]
externalscripts

**Comment by dnaeon** [comment]
Sergey,

As you are running with Zabbix 2.4.x, please consider using the Zabbix loadable module for vPoller as this one is better maintained and recommended for Zabbix versions 2.2.x and above.

Check the vPoller documentation on how to build and install the vPoller module for Zabbix.

 - http://vpoller.readthedocs.org/en/latest/vpoller-zabbix.html

Thanks,
Marin

**Comment by georg1ch** [comment]
I will try in the near future
thank you

**Comment by dnaeon** [comment]
No problem.

If you run into any issues with the installation of the loadable module for vPoller, feel free to report it and I'll try to assist you :)

Thanks,
Marin
