### ISSUE TITLE
zabbix-vsphere-import

### ISSUE THREAD

**Issue by georg1ch** [dnaeon/py-vpoller#121]
Hi Marin
When importing objects vSphere
get the same error:

```bash
[root @ ##### ~] # python2.7 ./zabbix-vsphere-import -f zabbix-vsphere-import-host.yamal
Traceback (most recent call last):
   File "./zabbix-vsphere-import", line 654, in <module>
     main ()
   File "./zabbix-vsphere-import", line 633, in main
     with open (args ['- file'], 'r') as f:
TypeError: coercing to Unicode: need string or buffer, list found
```
Regards,
Sergey

**Comment by dnaeon** [comment]
Hey Sergey,

Please post your `zabbix-vsphere-import.yaml` file, it seems there is an issue with your config file.

Thanks,
Marin

**Comment by georg1ch** [comment]
---
vsphere:
  hostname: my.vc

vpoller:
  endpoint: tcp://zabbix_srv_ip_vpoller_proxy:10123
  retries: 3
  timeout: 3000

zabbix:
  hostname: http://zabbix_srv_ip_vpoller_proxy/zabbix
  username: Admin
  password: zabbix

  vsphere_object_host:
    templates:
      - Template VMware vSphere Hypervisor - vPoller Native
    macros:
      VSPHERE.HOST: my.vc
    groups:
      - Hypervisors

  vsphere_object_vm:
    templates:
      - Template VMware vSphere Virtual Machine - vPoller Native
    macros:
      VSPHERE.HOST: my.vc
    groups:
      - Virtual Machines

  vsphere_object_datastore:
    templates:
      - Template VMware vSphere Datastore - vPoller Native
    macros:
      VSPHERE.HOST: my.vc
    groups:
      - Datastores

**Comment by dnaeon** [comment]
Are you using the latest `zabbix-vsphere-import` tool from the Github repo?

* https://github.com/dnaeon/py-vpoller/tree/master/extra/zabbix/vsphere-import

Have you done any changes to the script itself before running it?

This line here has a missing dash (`-`) in it, which shouldn't be the case.

```python
     with open (args ['- file'], 'r') as f:
```

Please grab the latest `zabbix-vsphere-import` tool from the Github repo and let me know how it goes.

Thanks,
Marin

**Comment by georg1ch** [comment]
I'm using the latest version.
But re-downloaded on your link.
Errors such as:
[root @ ##### ~] # python2.7 ./zabbix-vsphere-import -f zabbix-vsphere-import-host.yamal
Traceback (most recent call last):
   File "./zabbix-vsphere-import", line 654, in 
     main ()
   File "./zabbix-vsphere-import", line 633, in main
     with open (args ['- file'], 'r') as f:
TypeError: coercing to Unicode: need string or buffer, list found


I want to try to make the import of vSphere.
But while it is impossible because of these errors.
I want to try this option.
When monitoring all analyzing processes I run into the vSphere vCenter performance
CPU should be loaded to 100%
Growing queue.
and the log files zabbix_server.log see here these errors:
Did not receive response from vPoller, giving up.
vCenter (vcpu 4)
ESXi 96
VMs> 1000

**Comment by dnaeon** [comment]
That traceback looks really weird, because it doesn't look like to be coming from the stock `zabbix-vsphere-import` tool from the Github repo.

There are some whitespaces in this line, which makes me think there are some local changes done and the lines from the traceback are odd as well, because they don't match to the ones we have in the latest `zabbix-vsphere-import` tool.

```python
     with open (args ['- file'], 'r') as f:
```

As for having load on your vCenter, please submit a separate issue with all the details - CPU & Memory of the vCenter, load on the vCenter when vPoller is running and it is not running, how many Zabbix items you have, etc.

Thanks,
Marin

**Comment by georg1ch** [comment]
Marin,
not properly copied zabbix-vsphere-import
Now everything works

Thanks,
Sergey
