### ISSUE TITLE
Run import without Datastore?

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#126]
Hi Marin
Would it be possible to be able to run the import without the Datastores?
Currently our datastores are in disarray (naming wise lots of invalid paramaters in the name) and I was hoping to be able to disable for now that functionality?

Thanks!

**Comment by dnaeon** [comment]
Hi,

There is no command-line switch to disable that for now, but as a quick workaround simply comment out line 751 from the script.

* https://github.com/dnaeon/py-vpoller/blob/master/extra/zabbix/vsphere-import/zabbix-vsphere-import#L751

Regards,
Marin
