### ISSUE TITLE
monitoring host RAID

### ISSUE THREAD

**Issue by aplitec** [dnaeon/py-vpoller#127]
Hi,

we are testing vpoller with zabbix and all is working fine. Great Job.
Can we monitor de health of our hosts RAID volumes via CIM and vpoller ?
if so, what are the methods to do it ?
do you have any sample ?

Thanks

Josep

**Comment by dnaeon** [comment]
Hey Josep,

It is possible to monitor the health of your ESXi hardware by using the `HealthSystemRuntime` property, but this feature is currently not implemented in vPoller.

http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.HealthStatusSystem.Runtime.html

I will leave this ticket open, but I don't expect to be ready with it soon, as I'm busy with other projects at the moment.

You could also have a look at the existing vPoller methods/tasks and submit a pull-request with your changes.

Thanks,
Marin

**Comment by aplitec** [comment]
Hi Marin,

I haven't enough knowledge of python nor vmware api. So this seems a overwhelming task for me.

Maybe with some guidance and enough time...

Thanks

Josep

De: Marin Atanasov Nikolov [mailto:notifications@github.com]
Enviado el: miércoles, 25 de marzo de 2015 10:57
Para: dnaeon/py-vpoller
CC: Josep Borrell
Asunto: Re: [py-vpoller] monitoring host RAID (#127)


Hey Josep,

It is possible to monitor the health of your ESXi hardware by using the HealthSystemRuntime property, but this feature is currently not implemented in vPoller.

http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.HealthStatusSystem.Runtime.html

I will leave this ticket open, but I don't expect to be ready with it soon, as I'm busy with other projects at the moment.

You could also have a look at the existing vPoller methods/tasks and submit a pull-request with your changes.

Thanks,
Marin

**Comment by dnaeon** [comment]
Hey Josep,

I will see what I can do about it, but for now as I mentioned already I don't think I will be able to complete this soon as I have other stuff to take care of on my plate already.

Regards,
Marin
