### ISSUE TITLE
Performance Counters report inconsistent key values between Vcenter hosts

### ISSUE THREAD

**Issue by jgerry2002** [dnaeon/py-vpoller#129]
I have multiple vcenter hosts - when I poll for performance data the key value numbers do not match from vcenter server to vcenter server. This makes it very difficult to create common templates for multiple vcenter servers. Is there another way to reference the key data?

Here is an Example:

Query of:
```bash
vpoller-client --method host.perf.metric.get --vsphere-host <VCENTER.SERVER> --name <ESXHOST> --counter-id 433 
```
Is not the same from Vcenter Server 1 vs Vcenter Server 2 etc. I can't template any of these keys.

Here is what vpoller gets from each Vcenter. 

Vcenter server 1:
```json
{
      "rollupType": "average",
      "statsType": "absolute",
      "unitInfo": {
        "summary": "Megabytes",
        "key": "megaBytes",
        "label": "MB"
      },
      "groupInfo": {
        "summary": "Memory",
        "key": "mem",
        "label": "Memory"
      },
      "nameInfo": {
        "summary": "Total amount of memory reservation used by and available for powered-on virtual machines and vSphere services on the host",
        "key": "totalCapacity",
        "label": "Total capacity"
      },
      "key": 399,
      "level": 2,
      "perDeviceLevel": 3
    },
```
Vcenter Server 2:
```json
{
      "rollupType": "average",
      "statsType": "absolute",
      "unitInfo": {
        "summary": "Megabytes",
        "key": "megaBytes",
        "label": "MB"
      },
      "groupInfo": {
        "summary": "Memory",
        "key": "mem",
        "label": "Memory"
      },
      "nameInfo": {
        "summary": "Total amount of memory reservation used by and available for powered-on virtual machines and vSphere services on the host",
        "key": "totalCapacity",
        "label": "Total capacity"
      },
      "key": 433,
      "level": 2,
      "perDeviceLevel": 3
    },

```

**Comment by dnaeon** [comment]
Are both vCenter servers running the same vCenter release?

The information that vPoller returns is retrieved from vCenter itself, so if that's how vCenter returns it then that's how vPoller presents it as well.

The fact that both vCenters return different keys for the same performance counter makes me think these vCenters are running different versions.

Is that the case?

Thanks,
Marin

**Comment by jgerry2002** [comment]
That was the first thing I checked.

All my vcenters are precisely at the same patch level. Every Vcenter gives me different order in the key pairs. 

Build is 5.5 - 2442329

**Comment by jgerry2002** [comment]
Any thoughts how to solve this? Is there another way to query the performance data by using key name instead?

**Comment by dnaeon** [comment]
I cannot think of anything else right now that could explain why they return different keys for the same performance counter.

I've checked in a few vCenters (running same versions) and the performance counters returned are all the same in all vCenters.

In your vCenters what version of ESXi hosts are you running with? Same ESXi version everywhere or a mix of versions?

**Comment by jgerry2002** [comment]
I ran through all of my vcenters. I think there has to be some patch or setting difference that isnt obvious:

Site 1: totalCapacity = 410
Site 2: totalCapacity = 410
Site 3: totalCapacity = 376
Site 4: totalCapacity = 410
Site 5: totalCapacity = 410
Site 6: totalCapacity = 410
Site 7: totalCapacity = 376
Site 8: totalCapacity = 376

**Comment by dnaeon** [comment]
Can you run this vPoller command against your vCenters and see if there are any differences between them?

```bash
$ vpoller-client --method about --vsphere-host <vcenter-host> --properties fullName,version,apiType,apiVersion
```

**Comment by jgerry2002** [comment]
7 of 8 Vcenters give me:
VMware vCenter Server 5.5.0 build-2442329

1 of 8 gives me:
VMware vCenter Server 5.5.0 build-2183111

1) The one with 21831111 is reporting keys like the others (410)
2) The ones on 2442329 - 3 of them have the counter issue and have a different order as posted above (totalCapacity is 376)

**Comment by jgerry2002** [comment]
Further issues - does not really seem to follow much of a patten, depending on the counter:

Site 1: lowfreethreshold = 438
Site 2: lowfreethreshold = 438
Site 3: lowfreethreshold = 403
Site 4: lowfreethreshold = 437
Site 5: lowfreethreshold = 437
Site 6: lowfreethreshold = 438
Site 7: lowfreethreshold = 404
Site 8: lowfreethreshold = 404

**Comment by dnaeon** [comment]
@jgerry2002, I'll be refactoring how performance counters work with vPoller in order to make it work in a more standard way, e.g. instead of passing counter-id keys as it is now, you will be providing a counter in the `<counter-name>.<counter-group>.<unit>` form, for example `cpu.usage.percent`.

I will leave this issue open until I find some spare time to do the needed changes.

**Comment by jgerry2002** [comment]
Thanks, I have a large monitoring project that I can test out your changes whenever you find the time.

**Comment by dnaeon** [comment]
@jgerry2002 Please upgrade vPoller to version 0.5.7, which now fixes these issues.

Also, make sure to rebuild the ``vpoller.so`` Zabbix module and check the documentation on how to use the new performance counters in vPoller.

Here's just an example how to get the number of Virtual Machine power on operations for a datacenter.

```bash
 vpoller-client --method datacenter.perf.metric.get --vsphere-host vc01.example.org \
             --name MyDatacenter --counter vmop.numPoweron.number.latest --perf-interval "Past day"
```

Thanks,
Marin
