### ISSUE TITLE
vpoller can get every virtual machine's simple CPU & Memory info ？

### ISSUE THREAD

**Issue by tnndlbmu** [dnaeon/py-vpoller#135]
Hey Marin,
may i know how to use vpoller-client tools to get every VM's CPU & Memory info ?
like cpu: 16cores memory:16G, etc.
thank you.

**Comment by dnaeon** [comment]
@tnndlbmu Here's how you can get that info with vPoller.

Run this command, which will collect the properties for CPU cores and memory for each discovered VM.

```bash
$ vpoller-client --method vm.discover --vsphere-host <vcenter> --properties config.hardware.numCPU,config.hardware.memoryMB
```

Regards,
Marin

**Comment by tnndlbmu** [comment]
thanks, it works.
