### ISSUE TITLE
How to get the parent folder of a datacenter?

### ISSUE THREAD

**Issue by Joergz** [dnaeon/py-vpoller#136]
Hello together,

is it possible to get the parent folder of an vSphere datacenter using the vpoller-client? 

vpoller-client --method datacenter.get --vsphere-host VC --name DCNAME --properties name,overallStatus

I think, there is no property available for the folder. 

Best regards,
Jörg

**Comment by dnaeon** [comment]
Hi,

Using the ``parent.name`` attribute of a ``vim.Datacenter`` managed entity would return you the folder of a Datacenter, but unfortunately that property is not something we can collect using a property collector.

The way it can be done though is by introducing a new vPoller method for taking care of this. I will leave the ticket open for now, but I don't expect to be ready with it soon.

**Comment by dnaeon** [comment]
Closing this one as I don't have enough bandwidth to work on it. If anyone is willing to pick this up, please feel free to do so.
