### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by Epaphus** [dnaeon/py-vpoller#137]
Hi,

Is there away to find out what snapshots a VM has and setup some alerts based on them?
I didn't see anything about snapshots under the supported methords - http://vpoller.readthedocs.org/en/latest/methods.html

Looking for alerts on snapshot age and size.

Thanks

**Comment by dnaeon** [comment]
Hey,

You should create such alarm first in your vCenter, then using vPoller and the `vm.alarm.get` method you should be able to catch these alarms.

Regards,
Marin
