### ISSUE TITLE
Is it possible to view the tags of a VM as a property?

### ISSUE THREAD

**Issue by mtward** [dnaeon/py-vpoller#140]
Is it possible to view the tags of a VM as a property?

**Comment by dnaeon** [comment]
Hi,

Each managed entity has a `tag` attribute that is supposed to contain the assigned tags to objects, unfortunately this is currently not possible to get the tags using `pyVmomi` and as a result vPoller cannot get them either.

See this thread for more info.

http://pyvmomi.2338814.n4.nabble.com/virtual-machine-tags-td18.html

Regards,
Marin

**Comment by michaelrice** [comment]
Hey @dnaeon the tagging API isnt even part of the standard API, but vmware did release this http://developercenter.vmware.com/web/sdk/60/vcloudsuite-python which does include tagging api support, and uses pyvmomi but does require 6.0+

**Comment by dnaeon** [comment]
@michaelrice thanks, I wasn't aware of that!

Will check it out soon! :)
