### ISSUE TITLE
zabbix-vsphere-import

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#143]
Hi Marin
Is it possible to have the script to exclude importing templates?

Thanks,
Bradley

**Comment by dnaeon** [comment]
Hey Bradley,

Sure, I'll look into this and update the script soon.

Thanks,
Marin

**Comment by dnaeon** [comment]
Bradley,

Please grab the latest version of `zabbix-vsphere-import` and let me know how it goes.

Thanks,
Marin

**Comment by bundaburg** [comment]
Works perfectly, Thanks!
