### ISSUE TITLE
vpoller: VM DISK IO

### ISSUE THREAD

**Issue by Nefelim4ag** [dnaeon/py-vpoller#144]
Zabbix can find disks by lldp and return IO from him like:
vmware.vm.vfs.dev.write[{$URL},{$VMID},{#DISKNAME},bps]
May be vPoller can do it, by someway? (i don't find it in Templates)

**Comment by dnaeon** [comment]
You can already discover the existing disks and create Zabbix items to monitor the performance using the performance metrics items.

For more info check this documentation and the existing example performance items from the Zabbix templates.

* http://vpoller.readthedocs.org/en/latest/examples.html#performance-metrics
