### ISSUE TITLE
zabbix-vsphere-import - Cluster names and VMs within it.

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#146]
Hi Marin
Just a quick question regarding the VM's and ESX hosts.  Once imported the go into a host group which is the name of the cluster.  

My question is around when a group of servers get moved to a new cluster name.  The ESX and VM still exists as an entry in Zabbix.  When the import runs it correctly creates the new cluster as a host group.  But the VMs and ESX remain in the old host group.  Is there an easy way to put in a check that the items are indeed belonging to the correct host group?

Many Thanks,

**Comment by dnaeon** [comment]
Hey Bradley,

Sure, I will look into this when I have some spare time.

Thanks,
Marin

**Comment by dnaeon** [comment]
Closing this one as I don't have enough bandwidth to work on it. If anyone is willing to pick this up, please feel free to do so.
