### ISSUE TITLE
Trouble retrieving Datastore IOPS stats

### ISSUE THREAD

**Issue by AceJase** [dnaeon/py-vpoller#148]
Loving vPoller - much better than the lacklustre offering by Zabbix natively. However, one of the key reasons I wanted vPoller was the ability to pull up arbitrary performance stats. I've been struggling to find the right incantation for the key to get the average read & write IOPS per Datastore.

I started playing around with vpoller-client and found a bug immediately. I don't really know/have the time to do a patch/pull but it is a very simple typo - line 2777 of the file vsphere.py has the variable interval_name referenced as interval_namea (the 'a' is the typo).

After changing it at my end and confirming I can now get further into the process, I am now getting stuck with errors about the perf-interval:
```
vpoller-client --method datastore.perf.metric.get --vsphere-host vcenter.hostname.redacted --name "ds:///vmfs/volumes/4eba7ba2-18d545ca-22b0-d4bed9a8b365/" --counter datastore.numberReadAveraged.number.average --instance "naa.6782bcb0005a6157000002f94eb9288b" --perf-interval "Past Day"
{"msg": "Historical interval Past Day does not exists", "success": 1}
```

I get that result trying "Past Day", PastDay and 1. Have also tried similar variations (Past Week, Month, Year).

Can you advise what the problem could be or am I just not understanding how to do this correctly?

**Comment by dnaeon** [comment]
Hey @AceJase thanks for reporting this issue!

I've just fixed the typo with `interval_namea` and pushed it to the vPoller repo.

As for the historical interval -- you are providing vPoller a wrong interval.

This is the result of running `perf.interval.info` method which gives me the available historical intervals.

```json
{
  "success": 0,
  "result": [
    {
      "name": "Past day",
      "key": 1,
      "level": 1,
      "enabled": true,
      "samplingPeriod": 300,
      "length": 86400
    },
    {
      "name": "Past week",
      "key": 2,
      "level": 1,
      "enabled": true,
      "samplingPeriod": 1800,
      "length": 604800
    },
    {
      "name": "Past month",
      "key": 3,
      "level": 1,
      "enabled": true,
      "samplingPeriod": 7200,
      "length": 2592000
    },
    {
      "name": "Past year",
      "key": 4,
      "level": 1,
      "enabled": true,
      "samplingPeriod": 86400,
      "length": 31536000
    }
  ],
  "msg": "Successfully retrieved performance historical intervals"
}
```

Note that in the above result the valid interval name is `Past day` and not `Past Day` (`day` is in lower-case letters).

Thanks,
Marin

**Comment by AceJase** [comment]
Ah! That makes me feel a little silly, but glad it is something simple. I'll give that a whirl when I'm back at work.

Keep up the great work! :)
