### ISSUE TITLE
how to monitor / import hosts from two separate vcenter servers?

### ISSUE THREAD

**Issue by protofab** [dnaeon/py-vpoller#150]
zabbix integration .... what is the recommended approach to monitoring multiple vcenter servers in zabbix? I have one vcenter already configured and have imported hosts into zabbix.  I wish to add a second vcenter and then import it's hosts into zabbix.  can I use a single zabbix-vsphere-import.yaml or do I need separate import files? for example, can I call from cron 2 differnet .yaml import scripts, each corresponding to a vcenter server? 

secondly, shouldn't I be able to add the 2nd vcenter server to my vconnector.db, with appropriate credentials, and query via vpoller-client ? I'm getting user login errors, but have verified credentials using the following test_vconnector.py script:

more test_vconnector.py
import requests
requests.packages.urllib3.disable_warnings()

import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context
from vconnector.core import VConnector

agent = VConnector(user=MyuserID, pwd=Mypasswd, host=my.host.name')
hosts = agent.get_host_view().view
print hosts

I'm getting "task about failed" responses for the events in latest data after having added the 2nd vcenter to zabbix.

**Comment by bundaburg** [comment]
I have connected to multiple VC by adding a 2nd host within the vconnector-cli then creating a 2nd yaml file for the other VC

**Comment by dnaeon** [comment]
As @bundaburg mentioned you should add your host to the `vconnector.db` database file and enable the agent. If you want to continuously import objects using the `zabbix-vsphere-import` tool you should create a separate YAML file for that vCenter as well.

**Comment by protofab** [comment]
thanks @bundaburg, i'll give that a try.  I've got to figure out why my connection is failing at the moment or the .yaml import is a non-issue. 

credentials in vconnector.db are identical and appropriate and here's my output from the above test script:
