### ISSUE TITLE
missing graphs / no data traffic for vpoller vm.perf.metric.get

### ISSUE THREAD

**Issue by protofab** [dnaeon/py-vpoller#151]
i'm not seeing any performance data from my vpoller queries of networking on esx hosts, vms, etc. 

any reason this data wouldn't be available by default? i have networking data from other monitored devices (via snmp mostly),  just not from vpoller.

thanks, george

**Comment by dnaeon** [comment]
Hey George,

Can you be more specific to which performance metrics are you referring to,
e.g names of counters you are trying to get, Zabbix items, etc?

What is the release of the vsphere host from which you are collecting
metrics?

Have you tried getting the metrics using vpoller-client?

Thanks,
Marin

**Comment by protofab** [comment]
sure, apologies.  for example, the key for "Network" in a vm under the vPoller Native Template

vpoller["vm.perf.metric.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "value", "", "", "", "148", "", ""]

returns no data.

**Comment by dnaeon** [comment]
Hey,

That Zabbix item is using the old way of retrieving performance counters. Please update your Zabbix templates with the ones from the Github repo.

The new performance counter items are using the counter names instead of counter ids.

Thanks,
Marin

**Comment by protofab** [comment]
from here?:

https://github.com/dnaeon/py-vpoller/tree/master/extra/zabbix/templates/vpoller-templates-native-2.4

**Comment by dnaeon** [comment]
Yes, these are the templates.

**Comment by protofab** [comment]
Marin, I imported the templates reference above. I chose to update / replace during the process but did not get the updated Key.  so, I have removed all hosts and vpoller based resources from zabbix.  I removed the templates and re-imported.

now, with just a vshpere host added, and using the vSphere Hypervisor - vPoller Native template, I still get the vpoller["host.perf.metric.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "value", "", "", "", "149", "", ""] formatted key.

what should it be? i don't want to reimport from my .yaml file until I'm sure I'm using the correct templates, so I've turned off my cron job at the moment.






.

**Comment by dnaeon** [comment]
Hey George,

I've just checked the templates, it seems I've forgotten to update the templates for Zabbix 2.4, the ones for version 2.2.x are updated though.

Please either try to import the templates from 2.2.x of Zabbix or check this commit here, where you can see the difference between the old and new performance metrics.

https://github.com/dnaeon/py-vpoller/commit/d5c7f9f035e9bb1628d227751378c189636c0571

Thanks,
Marin

**Comment by protofab** [comment]
Marin, thanks.  I updated using the 2.2.x templates and i now am seeing Network perf data for my vSphere member devices. Many thanks.

Until my next newbie quest....

**Comment by Emmanux** [comment]
Please update readthedocs.io and the pip repository. So many work hours lost trying to figure out what is wrong... it's always the same, those are not up to date.

**Comment by dnaeon** [comment]
You can always install the latest code from this repo.
