### ISSUE TITLE
zabbix-vsphere-import - Ignore powered off machines

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#153]
Hi,
Is it possible to ignore machines that are in a powered off state for the vsphere import?

Thanks!

**Comment by dnaeon** [comment]
Sure, I'll check that out soon.

**Comment by bundaburg** [comment]
Thank you

**Comment by dnaeon** [comment]
@bundaburg please get the latest version of the script and let me know how it goes.

**Comment by takenek** [comment]
Hey,
So now please add remove turnoff machine from Zabbix because now You give option to don`t import but what about old machineswho was imported via old zabbix-vsphere-import ?

Thanks

**Comment by bundaburg** [comment]
Thanks its works fine.
@takenek i just dumped the servers that are powered off and manually removed them.

**Comment by takenek** [comment]
@bundaburg Yes You can do this manually if You got few only servers....
I got 100+ powered off....

Thanks

**Comment by dnaeon** [comment]
@takenek you should be able to filter the VMs from the Zabbix dashboard which are currently in poweredOff state and then bulk-delete them.
