### ISSUE TITLE
graph templates returning no data- wrong template versions?

### ISSUE THREAD

**Issue by protofab** [dnaeon/py-vpoller#155]
hi, i've been building some screens using simple graph resources. when i select CPU Usage (Percentage) for a virtual machine, which has vpoller["vm.cpu.usage.percent", "{$VSPHERE.HOST}", "{HOST.HOST}", "vm.cpu.usage.percent", "null"] as the parameter, i'm getting [no data] returned. 

same for balooned memory and other resources.

last time i had an issue like this, template versions were mis-matched see issue #151. 

can you update the templates for version 2.4 or advise if this isn't the issue. thanks in advance.

george

**Comment by dnaeon** [comment]
Hey George,

This is most likely a template mismatch between the 2.2.x and 2.4.x templates. Please grab the the templates from 2.2.x which should contain the right items. Unfortunately I don't have enough time to do that myself, so if you update the template yourself please open a pull-request with the latest changes and I will merge it.

Thanks,
Marin
