### ISSUE TITLE
vsan.health.get zabbix template

### ISSUE THREAD

**Issue by avs262** [dnaeon/py-vpoller#159]
There isn't a Zabbix template for the vsan.health.get task so I've been trying to create the task manually without success. Has anyone configured Zabbix to monitor vSAN? If so, what does your vpoller/zabbix key look like?

**Comment by dnaeon** [comment]
Hey @avs262, just create a new Zabbix item based on the already existing ones from the templates.

What do you got so far?

**Comment by avs262** [comment]
Here's what I've got: 

vpoller["vsan.health.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "health", "null"]

**Comment by dnaeon** [comment]
The item look okay. Btw, you could remove the last "null", so your item should become

`vpoller["vsan.health.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "health"]`

Do you get any errors reported in Zabbix or from the vPoller logs?

**Comment by avs262** [comment]
Issue on my end. I changed the "Type of information" within Zabbix to "text' and it's working great now.

**Comment by dnaeon** [comment]
Cool, glad you figured it out :)
