### ISSUE TITLE
zabbix: Template VMware vSphere Clusters missing

### ISSUE THREAD

**Issue by olfway** [dnaeon/py-vpoller#160]
There is no Template VMware vSphere Clusters - *.xml in extra/zabbix/templates

could you add it, plz?

thanks!

**Comment by dnaeon** [comment]
You are referring to the `zabbix-vsphere-import` tool config, right?

@alextoderita was going to submit a pull request with that template after #158 PR, but I guess he forgot about that.

@alextoderita could you please commit the `Template VMware vSphere Clusters` template?

Thanks,
Marin

**Comment by kippie538** [comment]
[2015-12-15 17:16:26,046] - WARNING - Unable to find 'Template VMware vSphere Clusters - vPoller Native' template
[2015-12-15 17:16:26,046] - WARNING - No valid templates found for 'vsphere_object_clusters_as_zabbix_host' config entry

The template is still missing, could someone help me to get the template.
Thx

**Comment by chises** [comment]
@kippie538 i think we are still waiting for @alextoderita to submit the pull request.. :-(

**Comment by dnaeon** [comment]
I've just disabled the vSphere Clusters as hosts in Zabbix because this is now affecting more and more people.

Once we have the template in the repo we can re-enable this feature. @alextoderita ?

**Comment by alextoderita** [comment]
Hi Guys, apologies for the late response. I just had a look in my Mabbix
web GUI v 2.4.6 and I can't find the export Tab under Configuration ->
Templates section; I can only see Import and Create template. Any idea why
or how it can be exported?
Regards,
Alex

**Comment by dnaeon** [comment]
Can you post a screenshot?

**Comment by alextoderita** [comment]
Sure, here it is.

**Comment by dnaeon** [comment]
The `Export` button should be at the bottom-left corner once you select the template.

**Comment by alextoderita** [comment]
Added, the pull request is: https://github.com/dnaeon/py-vpoller/pull/167

**Comment by dnaeon** [comment]
Thanks, merged already!

**Comment by Emmanux** [comment]
It's still missing in the 2.4 folder.
