### ISSUE TITLE
Do not monitor / include VM Templates with Zabbix

### ISSUE THREAD

**Issue by Bonn93** [dnaeon/py-vpoller#163]
Currently, when the discovery with zabbix kicks off, it includes VM Templates. Can a filter be introduced to not include these?

More of an enhancement, you can disable the host manually as a workaround. 

![image](https://cloud.githubusercontent.com/assets/6925963/11492221/1dfb0f74-983e-11e5-9e8d-1c865a2b0b1a.png)

**Comment by dnaeon** [comment]
@Bonn93 Yep, we shouldn't import templates. I will update the script soon to reflect that.

**Comment by dnaeon** [comment]
Actually this has already been implemented.

* https://github.com/dnaeon/py-vpoller/blob/master/extra/zabbix/vsphere-import/zabbix-vsphere-import#L521
