### ISSUE TITLE
zabbix-vsphere-import - skip specific machines

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#164]
Hi there,
I was wondering if it would be possible to add a variable to not import machines with a certain name?  Whether this be via a variable (./import --exclude Server1, Server2) or be able to exclude all servers in an input file?

**Comment by dnaeon** [comment]
Yep, that can definitely be done within the existing YAML file that the script uses.

Will get it done, but I don't expect to be ready with it soon, as I'm busy with other stuff as well.

**Comment by dnaeon** [comment]
Closing this one, as I don't have the bandwidth to work on it. If anyone else is willing to pick this up, please do so.
