### ISSUE TITLE
vPoller vSphere 6 Appliance

### ISSUE THREAD

**Issue by chises** [dnaeon/py-vpoller#166]
Hi,
Just a short question. I am sorry but i habe no idea where to post it so I will try it here. Bsphere 5.x is working great but @ vsphere 6 I always get "inside username or password" in the worker log. Is someone using vpoller with vsphere 6 (U1) an the server appliance? 
Best regard and thanks!

**Comment by dnaeon** [comment]
Please post some logs with the errors you are getting, so that we can have
a look at them.

Thanks,
Marin

**Comment by chises** [comment]
Ok, no Problem. Thank you for your Support!

root@bss-s-zab01:/usr/share/py-vpoller/extra/zabbix/vsphere-import# vconnector-cli -v
0.4.0
root@bss-s-zab01:/usr/share/py-vpoller/extra/zabbix/vsphere-import# vpoller-worker -v
0.5.8
root@bss-s-zab01:/usr/share/py-vpoller/extra/zabbix/vsphere-import# vpoller-proxy -v
0.5.8

root@bss-s-zab01:/usr/share/py-vpoller/extra/zabbix/vsphere-import# vconnector-cli get
+-----------------------+---------------+------------+-----------+
| Hostname              | Username      | Password   |   Enabled |
+=======================+===============+============+===========+
| bss-s-vca01.k*** | zabbix@k**** | ******     |         1 |
+-----------------------+---------------+------------+-----------+


root@bss-s-zab01:/usr/share/py-vpoller/extra/zabbix/vsphere-import# vpoller-client --method datastore.discover --vsphere-host 'bss-s-vca01.kremer.de'
{"msg": "Task datastore.discover failed", "traceback": "Traceback (most recent call last):\n  File \"build/bdist.linux-x86_64/egg/vpoller/task/decorators.py\", line 55, in wrapper\n    result = fn(*args, **kwargs)\n  File \"build/bdist.linux-x86_64/egg/vpoller/vsphere/tasks.py\", line 2516, in datastore_discover\n    obj_type=pyVmomi.vim.Datastore\n  File \"build/bdist.linux-x86_64/egg/vpoller/vsphere/tasks.py\", line 76, in _discover_objects\n    view_ref = agent.get_container_view(obj_type=[obj_type])\n  File \"build/bdist.linux-x86_64/egg/vconnector/core.py\", line 320, in get_container_view\n    container = self.si.content.rootFolder\n  File \"build/bdist.linux-x86_64/egg/vconnector/core.py\", line 106, in si\n    self.connect()\n  File \"build/bdist.linux-x86_64/egg/vconnector/core.py\", line 141, in connect\n    pwd=self.pwd\n  File \"/usr/local/lib/python2.7/dist-packages/pyvmomi-5.5.0.2014.1.1-py2.7.egg/pyVim/connect.py\", line 590, in SmartConnect\n    path=path)\n  File \"/usr/local/lib/python2.7/dist-packages/pyvmomi-5.5.0.2014.1.1-py2.7.egg/pyVim/connect.py\", line 234, in Connect\n    keyFile, certFile)\n  File \"/usr/local/lib/python2.7/dist-packages/pyvmomi-5.5.0.2014.1.1-py2.7.egg/pyVim/connect.py\", line 333, in __Login\n    x = content.sessionManager.Login(user, pwd, None)\n  File \"/usr/local/lib/python2.7/dist-packages/pyvmomi-5.5.0.2014.1.1-py2.7.egg/pyVmomi/VmomiSupport.py\", line 566, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/pyvmomi-5.5.0.2014.1.1-py2.7.egg/pyVmomi/VmomiSupport.py\", line 375, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File \"/usr/local/lib/python2.7/dist-packages/pyvmomi-5.5.0.2014.1.1-py2.7.egg/pyVmomi/SoapAdapter.py\", line 1301, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\nvim.fault.InvalidLogin: (vim.fault.InvalidLogin) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Cannot complete login due to an incorrect user name or password.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n}\n", "success": 1}

I used different Users. All of them are working in the vSphere Web Client + vSphere Client. But i had no luck with vPoller. What are the "best practise" for the username+password? is a LDAP username + Password official Support? 

Really thank you for your Support!

**Comment by dnaeon** [comment]
As a general rule always use an account that has read-only access to the vCenter host. vPoller does not require any write privileges, so just stick to a read-only account for vPoller.

Any user that has access to the web client should be able to be used with vPoller.

Can you upgrade your vPoller to the latest release, which is 0.6.1?

**Comment by chises** [comment]
it seem that you need to restart the vpoller-worker and/or Proxy if you Change vconnector credentials. i deployed the vm again with the "old" Version 0.5.8 and after the process restart it is working like a charm.
Same with Version 0.6.1: it was my fault.

i will Close that issue, thank you for your Support!

**Comment by dnaeon** [comment]
Correct, the vconnector database is consulted during vPoller Worker start, so if you do any changes to it after you've started your Workers, you need to restart them in order to get the new changes.

Glad you've figured it out, btw! :)
