### ISSUE TITLE
get "virtualDisk.totalReadLatency.millisecond.average"

### ISSUE THREAD

**Issue by chises** [dnaeon/py-vpoller#169]
In the Method:
vpoller-client --method vm.perf.metric.info --vsphere-host ste-s-***.crimson.local --name ste-s-** --helper vpoller.helpers.zabbix
i get the following:
[...]
{"{#VSPHERE.VM.PERF.METRIC.INSTANCE}": "", "{#VSPHERE.VM.PERF.METRIC.COUNTERID}": "rescpu.sampleCount.number.lates{#VSPHERE.VM.PERF.METRIC.INSTANCE}": "scsi0:0", "{#VSPHERE.VM.PERF.METRIC.COUNTERID}": "virtualDisk.totalReadLatency.millisecond.average"}, 
[..]

how can i get the value for "virtualDisk.totalReadLatency.millisecond.average"

following does not work:
root@ste-s-***:~# vpoller-client --method vm.perf.metric.get --vsphere-host ste-s-*** --name ste-s-*** --counter "virtualDisk.totalReadLatency.millisecond.average"
{"msg": "Successfully retrieved performance metrics", "result": [], "success": 0}

Other Stuff is working:
root@ste-s-***:~# vpoller-client --method vm.perf.metric.get --vsphere-host ste-s-*** --name ste-s-*** --counter "net.usage.kiloBytesPerSecond.average"
{"msg": "Successfully retrieved performance metrics", "result": [{"timestamp": "2015-12-18 10:41:40+00:00", "counterId": "net.usage.kiloBytesPerSecond.average", "interval": 20, "value": 14, "instance": ""}], "success": 0}

Thanks for help!

**Comment by dnaeon** [comment]
What's the vSphere version you are running with?

Related to this one?

* https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2119264

**Comment by sirmaxru** [comment]
This is how you can do this for VMHost:
vpoller-client --method host.perf.metric.get --vsphere-host vspherehost --name VMHost --counter datastore.datastoreNormalWriteLatency.number.latest --instance 564cb91e-d17811e0-8bc0-3ca82a0ceb64
instance 564cb91e-d17811e0-8bc0-3ca82a0ceb64 - id of datastore
