### ISSUE TITLE
Datacenter auto discovery alarms

### ISSUE THREAD

**Issue by bundaburg** [dnaeon/py-vpoller#173]
Upon importing the latest template Template-VMware-vSphere-Datacenter-vPoller-Native.xml and importing datacenters into Zabbix, the discovery fails with error: Invalid number of key parameters.

I have upgraded all components:
Requirement already up-to-date: vpoller in /usr/lib/python2.7/site-packages
Requirement already up-to-date: pyzmq>=14.3.1 in /usr/lib64/python2.7/site-packages (from vpoller)
Requirement already up-to-date: docopt>=0.6.2 in /usr/lib/python2.7/site-packages (from vpoller)
Requirement already up-to-date: pyvmomi>=6.0.0 in /usr/lib/python2.7/site-packages (from vpoller)
Requirement already up-to-date: vconnector>=0.4.3 in /usr/lib/python2.7/site-packages (from vpoller)
Requirement already up-to-date: requests>=2.3.0 in /usr/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller)
Requirement already up-to-date: six>=1.7.3 in /usr/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller)
Requirement already up-to-date: tabulate>=0.7.3 in /usr/lib/python2.7/site-packages (from vconnector>=0.4.3->vpoller)

Any ideas?

Thanks

**Comment by dnaeon** [comment]
Hey @bundaburg ,

Can you please show the items that you have for `vim.Datacenter` objects and the exact error.

Can you run `vpoller-client` from the command-line and see what happens?

**Comment by bundaburg** [comment]
Thanks,
Im not sure what you mean by the vim.datacenter objects.
Heres the output from the vpoller-client:

[root@xxx ~]# vpoller-client --method datacenter.alarm.get --vsphere-host xxx --name xxx
{"msg": "Successfully retrieved alarms", "result": [{"info": "Host Baseboard Management Controller status", "acknowledgedByUser": null, "acknowledged": false, "entity": "xxx.com", "key": "alarm-37.host-1072", "time": "2015-12-17 12:56:50.057000+00:00", "overallStatus": "yellow"}, {"info": "Datastore usage on disk", "acknowledgedByUser": null, "acknowledged": false, "entity": "Raid5_1.9Tb", "key": "alarm-8.datastore-1348", "time": "2015-09-10 08:34:23.876999+00:00", "overallStatus": "yellow"}, {"info": "Datastore usage on disk", "acknowledgedByUser": null, "acknowledged": false, "entity": "RAID1-VOL3", "key": "alarm-8.datastore-331", "time": "2015-06-18 01:30:34.162999+00:00", "overallStatus": "yellow"}, {"info": "Datastore usage on disk", "acknowledgedByUser": null, "acknowledged": false, "entity": "RAID5-VOL4", "key": "alarm-8.datastore-332", "time": "2015-07-02 04:43:01.052999+00:00", "overallStatus": "yellow"}, {"info": "Datastore usage on disk", "acknowledgedByUser": null, "acknowledged": false, "entity": "RAID5-VOL5", "key": "alarm-8.datastore-333", "time": "2015-11-25 20:56:46.116999+00:00", "overallStatus": "red"}, {"info": "Datastore usage on disk", "acknowledgedByUser": null, "acknowledged": false, "entity": "RAID5-VOL6", "key": "alarm-8.datastore-334", "time": "2015-07-27 00:10:48.533000+00:00", "overallStatus": "yellow"}, {"info": "Datastore usage on disk", "acknowledgedByUser": null, "acknowledged": false, "entity": "DR-SAS-VOL1", "key": "alarm-8.datastore-390", "time": "2015-10-06 02:21:03.913000+00:00", "overallStatus": "yellow"}], "success": 0}

**Comment by bundaburg** [comment]
[root@xxx ~]# vpoller-client --method datacenter.get --vsphere-host xxx --name London --properties name,overallStatus
{"msg": "Successfully retrieved object properties", "result": [{"overallStatus": "gray", "name": "London"}], "success": 0}

**Comment by bundaburg** [comment]
Just confirming what fails: 

Key: vpoller["datacenter.alarm.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "null"]
Item: Discover Datacenter Alarms

**Comment by dnaeon** [comment]
The item key looks good.

What is the version of the loadable module that you are using?

You should see that from the zabbix logs right after starting the zabbix server/proxy.

**Comment by bundaburg** [comment]
Its 0.5.7 loadable module

**Comment by bundaburg** [comment]
Okay im now having issues with the SSL module 
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed.

Looking through im running the latest:
Requirement already up-to-date: vpoller in /usr/lib/python2.7/site-packages
Requirement already up-to-date: pyzmq>=14.3.1 in /usr/lib64/python2.7/site-packages (from vpoller)
Requirement already up-to-date: docopt>=0.6.2 in /usr/lib/python2.7/site-packages (from vpoller)
Requirement already up-to-date: pyvmomi>=6.0.0 in /usr/lib/python2.7/site-packages (from vpoller)
Requirement already up-to-date: vconnector>=0.4.3 in /usr/lib/python2.7/site-packages (from vpoller)
Requirement already up-to-date: requests>=2.3.0 in /usr/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller)
Requirement already up-to-date: six>=1.7.3 in /usr/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller)
Requirement already up-to-date: tabulate>=0.7.3 in /usr/lib/python2.7/site-packages (from vconnector>=0.4.3->vpoller)

 and python 2.7.5

**Comment by dnaeon** [comment]
You should upgrade to at least Python 2.7.9. That is why the discovery rules are now failing.

pyVmomi has dropped support for Python versions prior 2.7.9:

https://github.com/vmware/pyvmomi/issues/329
https://github.com/vmware/pyvmomi/issues/306
https://github.com/vmware/vsphere-flocker-driver/issues/14

**Comment by bundaburg** [comment]
Thanks, i'll look at it in the morning, I just reverted back so that everything was operational again, will look at upgrade tomorrow.
Thanks for your assistance.
