### ISSUE TITLE
vPoller are not updated on zabbix3.0.0rc1 & zabbix3.0.0beta2

### ISSUE THREAD

**Issue by chises** [dnaeon/py-vpoller#174]
I used zabbix3.0.0alpha3 and alpha4 withourt any problems.
For test proposal i upgraded my server to rc1.
Problem: no vpoller zabbix items are updated. 
I already started a thread in the zabbix forum (https://www.zabbix.com/forum/showthread.php?t=52303). 
I can see this in the logs:

> 11373:20160203:221203.358 Sending task request to vPoller: { "method": "vm.disk.discover", "hostname": "HOSTNAME ", "name": "null", "properties": [ "null" ], "key": "(null)", "username": "(null)", "password": "(null)", "counter-name": "(null)", "instance": "(null)", "perf-interval": "(null)", "max-sample": "1", "helper": "vpoller.helpers.czabbix" }
> 11373:20160203:221203.362 Received reply from vPoller 

unfortunally i am stuck now :-( i can see the requests in the vpoller log without any errors. but the values are not updated in the zabbix database.

i changed a item to refresh every 10 seks. This works, every 10 sek a task is proceeded by vpoller but entry is written to the database.

is someone facing the same issue?
i am willing to share access to server to troubleshoot.

Thanks for help!

**Comment by dnaeon** [comment]
Hey @chises,

I don't have a Zabbix 3.0 environment yet, so can't really test things out. From the logs I can see that Zabbix sends a request and a reply is received from vPoller.

Do you see any errors at all either in the dashboard or the zabbix logs?

```bash
root@****:/home/miweber# zabbix_get -s 10.10.101.54 -p 10050 -k "vpoller[vm.disk.discover, HOSTAME, null, null]"
zabbix_get [11382]: Check access restrictions in Zabbix agent configuration
```

This one you should investigate and fix. Probably your configuration is not correct.

**Comment by chises** [comment]
hello @dnaeon 
really thank you for you fast answer.
the zabbix_get Problem is fixed. so i get a valid return value. 
in the logs i dont see any Errors.
i will clone my production zabbix Server and try again. i will come back to you and (if required) i can provide some credentials (public IP, user+login) to provide Access.

i just can see that the vpoller is "asked" for a Task, the Task is processed (cant see any Errors) but not 1 value is written to the database.

**Comment by chises** [comment]
Update: i can provide you ssh Access to a unix Maschine with clean zabbix3.0.0rc1 and vpoller installed and VMs imported.
http with public ip is working, too.

it would be greate if you could investigate some minutes to check it. I will sent a E-Mail if you agree. or we can use skype or something like that :)

**Comment by dnaeon** [comment]
Hey @chises,

Yeah, send me the login details.

I will try to check this up during the weekend, as during work days is pretty busy.

Thanks,
Marin

**Comment by chises** [comment]
@dnaeon 
Server Details were sent with email to  your gmail.com account.

**Comment by chises** [comment]
@dnaeon Problem solved.
i recompiled the vpoller module against the RC1 zabbix binaries and now it is working!

**Comment by dnaeon** [comment]
Yes, you should recompile the module after each Zabbix upgrade :)
