### ISSUE TITLE
VM Memory Usage Percentage

### ISSUE THREAD

**Issue by enricozocca** [dnaeon/py-vpoller#176]
Hi, 
in an old vpoller version I was able to use this item: vpoller-zabbix["-m", "vm.get", "-V", "{$VSPHERE.HOST}", "-n", "{HOST.NAME}", "-p", "summary.quickStats.guestMemoryUsagePercentage"]	

In the latest vpoller version I'm to be able to find this item. There is a way to recreate or calculate it?
I think that this is a basic item to check! 

Regards
Enrico Zocca

**Comment by dnaeon** [comment]
Hey Enrico,

You should be able to use the performance metric counters to get that with the latest vPoller templates, e.g. use the `cpu.usage.percent` counter to get that.

Make sure to check the performance counter chapter from the documentation:

 - http://vpoller.readthedocs.org/en/latest/examples.html#performance-metrics

Thanks,
Marin
