### ISSUE TITLE
How to Upgrade?

### ISSUE THREAD

**Issue by Lem3xcol** [dnaeon/py-vpoller#177]
Marin, have a nice day

I have a vpoller working with zabbix since some time ago and is working perfect. But this is an earlier version. I tried one of the last version and the improvements are more than evident. I wish to upgrade my old vpoller with the last release, How can do that? Do you have an upgrade document?

Thanks a lot

**Comment by Bonn93** [comment]
I've done mine with just pip upgrades. Make sure to re-compile / load the modules from Zabbix.

**Comment by dnaeon** [comment]
Yep, pip should handle the upgrades fine. Make sure to check the docs as well for any new features or config settings.

**Comment by Lem3xcol** [comment]
Thanks @Bonn93, thanks marin for the answers
But, my vpoller installation is very, very, very old. It is so old that the template uses the key vpoller-zabbix, and how should I proceed to use the new template with the new vpoller key?

**Comment by dnaeon** [comment]
Hey @Lem3xcol,

If you want to keep the historical data, then I'm afraid there's no easy way to transition to the newest version of vPoller.

What you could do though is slowly migrate the items to the new instance. To summarize the steps that would be:

1. Setup a separate instance with vPoller
2. Build  the loadable module for Zabbix
3. Import the new templates to a separate Zabbix instance
4. Start updating the Zabbix items one by one to the new format and verify they work
5. Repeat

More or less this should be all, but still that's going to be a lot of manual work. If you don't really care about the previous historical data, simply start over, which would be less of a deal.
