### ISSUE TITLE
Debian Packages unavailable

### ISSUE THREAD

**Issue by boffen** [dnaeon/py-vpoller#178]
Hi,

I'm not sure if this is the best place to report this, but according to http://vpoller.readthedocs.org/en/latest/installation.html there should be some debian packages available
"
In order to install vPoller from packages on a Debian GNU/Linux system you can use the Debian packages from the link below:
    Debian GNU/Linux packages for vPoller
"

The "Debian GNU/Linux packages for vPoller" text links to http://jenkins.unix-heaven.org/job/py-vpoller/

Unfortnently it looks like this host is down.
( http://www.downforeveryoneorjustme.com/http://jenkins.unix-heaven.org/job/py-vpoller/ also confirms this)

Are the debian packages available anywhere else?

**Comment by dnaeon** [comment]
Hey @boffen,

The Jenkins instance is up now, but it is recommended to use the packages from PyPI as they are more recent. Will update the documentation soon as well to reflect that change.
