### ISSUE TITLE
zabbix-vsphere-import issues

### ISSUE THREAD

**Issue by mholttech** [dnaeon/py-vpoller#182]
Hey,

So i'm working on building a Zabbix Docker container based off the Zabbix supported container, and it's going well but i'm running into some issues when running the zabbix-vsphere-import tool.  It appears as if it'll only process as many commands as their are workers running and then it dies saying

````
Traceback (most recent call last):
  File "/usr/local/bin/zabbix-vsphere-import", line 864, in <module>
    main()
  File "/usr/local/bin/zabbix-vsphere-import", line 857, in main
    zabbix.import_vsphere_vms()
  File "/usr/local/bin/zabbix-vsphere-import", line 520, in import_vsphere_vms
    vm_template = vpoller_data[0]['config.template']
KeyError: 'config.template'
````

my code can be found here https://github.com/MichaelHoltTech/docker-zabbix3-vpoller

any thoughts as to why it's crashing?

**Comment by dnaeon** [comment]
Can you tell me which was the last discovered object before you hit this error?

Seems like the `config.template` property is missing from the result, which is strange, since all `vim.VirtualMachine` objects should have this one.

Do you get this error if you run the import script outside the container?

**Comment by mholttech** [comment]
The logs are back at the office but it's always a vm and always random
every time I run it.  I have essentially an identical setup on a Ubuntu VM
and don't have any issues... I was just thinking though that I had to tweak
the supervisor conf slightly to work with the centos base of the official
Zabbix docker image so maybe something is up with that.  I'll manually run
the worker startup in the morning and see if the problem still occurs

On Thursday, March 31, 2016, Marin Atanasov Nikolov <
notifications@github.com> wrote:

> Can you tell me which was the last discovered object before you hit this
> error?
>
> Seems like the config.template property is missing from the result, which
> is strange, since all vim.VirtualMachine objects should have this one.
>
> Do you get this error if you run the import script outside the container?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dnaeon/py-vpoller/issues/182#issuecomment-204263502>
>


-- 
—————
Michael Holt
IT Systems Administrator
Network Systems Administrator
Mac Systems Administrator
Microsoft Office for Mac & iOS Accredited Support Professional 2015
661-621-5555

**Comment by dnaeon** [comment]
Also, what is the vCenter version that you have?

**Comment by mholttech** [comment]
I'm running v6u1

On Friday, April 1, 2016, Marin Atanasov Nikolov <notifications@github.com>
wrote:

> Also, what is the vCenter version that you have?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dnaeon/py-vpoller/issues/182#issuecomment-204298527>
>


-- 
—————
Michael Holt
IT Systems Administrator
Network Systems Administrator
Mac Systems Administrator
Microsoft Office for Mac & iOS Accredited Support Professional 2015
661-621-5555

**Comment by mholttech** [comment]
so I just confirmed, it appears to be something with supervisor running the process that's causing it to crash

**Comment by mholttech** [comment]
and now it's good to go.  Apparently Docker doesn't like supervisor redirecting the stdout and i've noticed the stopsignal doesn't seem to work with Centos so I went ahead and took that out of my vpoller supervisor conf file
