### ISSUE TITLE
vCenter is the bottleneck?

### ISSUE THREAD

**Issue by Bonn93** [dnaeon/py-vpoller#186]
I'm testing vPoller and Zabbix3 with a large vCenter ( several hundred vms / 25,000 objects ). We've noticed that vCenter has massive CPU usage once vPoller has been connected. Are there any options to reduce the load on the vCenter host?

* Item/Check intervals are mostly default
* vPoller is running with 4 threads ( matching the vm )

This has been noticed on both vCenter 5.5 and vCenter 6.0. 

A random question, what would a typical vCenter of that size have spec wise, cpu and memory? 

Graph attached was when our test instance was connected to vCenter early April.
![image](https://cloud.githubusercontent.com/assets/6925963/14839475/67c2844e-0c6e-11e6-9819-52d63c99fc64.png)

**Comment by dnaeon** [comment]
Hi,

You should check the official VMware documentation for properly sizing your vCenter server.

https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2052334

If you've got too many items, probably you could also start up another vPoller workers on a separate VM.

What's your vCenter specs atm?

**Comment by Bonn93** [comment]
It's sized properly, 4 CPUs and 16gb memory. 

Running more workers would still have that load in vcenter though?

**Comment by dnaeon** [comment]
Are you able to bump the resources a bit and give it more memory and vCPUs?

**Comment by Bonn93** [comment]
Having a bit of time, I've switched the vPoller services back on, and updated my intervals to at least 1 hour for Hypervisor/VM templates and also disabled a few items, however vCenter instantly blows up. 

![image](https://cloud.githubusercontent.com/assets/6925963/15105160/9c123f44-1602-11e6-8514-74bcecfbc1ec.png)

**Comment by Bonn93** [comment]
6 DataCenters, 15 hosts, 750 VMs. As above, vCenter is sized according to the VMware specification. We expected load on vCenter, however not that much. 

It would be great to see what exactly uses that CPU.

**Comment by Bonn93** [comment]
More testing, I've really gone to town on the intervals and tested with different vpoller thread counts. Seems there's nothing on the vPoller side that will help. I'm attempting to get more vCPUs added.

**Comment by dnaeon** [comment]
You should leave the vPoller concurrency to default. If your VM running vPoller has only 4 CPUs, then just leave the concurrency level to 4, don't over-size the concurrency level, as it may have negative results on both vPoller and the vCenter.
