### ISSUE TITLE
Wrong disk data from monitored virtualized Linux servers

### ISSUE THREAD

**Issue by Lem3xcol** [dnaeon/py-vpoller#188]
Hi Marin, nice to salute you again.

Here is my environment:
Vpoller: 0.6.1 on a Centos 6.5 server
VmWare: 5.5
Integrated with Zabbix 2.4

The problem:

If I run the following command:

> vpoller-client -m vm.disk.get -V vcenter -n srveduint -k / -p freeSpace

the output is:

> {"result": [{"name": "srveduint", "disk": {"diskPath": "/", "freeSpace": 14274543616}}], "success": 0, "msg": "Successfully retrieved properties"}

Which seems to be ok. However, if I check the free space directly in the queried server this is the output:

>`#` df -h
> Filesystem                                       Size   Used  Avail  Use% Mounted on
> /dev/mapper/vg_srveduint-lv_root   50G   36G    11G   77%     /

And this output shows a diferent amount of free space. Doing the maths (dividing by 1024), the output of the "vpoller-client" command shows 13.29Gb of free space and the command in the server shows 11Gb of free space. This is an aproximated difference of 2.2Gb between both outputs. Because I am running the command "vpoller-client", and I am having such difference, I don't think the problem can be Zabbix, but I can be  wrong.

At first though I double checked issues in the vCenter and in the virtualized server such vmware tools properly running or virtual server id's and labels, but everything seems to be ok. This server is not the only Linux server that exists in the vCenter, and all of them shows different free space in their filesystems, not only /, when I query them using the "vpoller-client" command and the OS command. Not all the servers shows the same diffence, in some of them the difference is 1.9Gb, in others 2.0Gb, in others 2.2GB. But I can say that the average of the diferences is 2Gb.

The total amount of space in each one of the filesystems is shown ok.

Going further, I installed the zabbix client in one of the virtual Linux servers monitored by vpoller, so that server is monitored using vpoller and also zabbix client. In this server, the free space in the filesystems reported by the Zabbix client is shown accurate, while the same item shown by vpoller shows an average of 2Gb more than the real free space in all the filesystems.

In my VmWare environment I have virtualized windows servers along with Linux servers. I checked also the windows servers and in those servers this issue does not happens, only in the Linux servers.

Thanks since now for the always nice help you gave us. 

Best regards,

Luis Morales

**Comment by dnaeon** [comment]
Hey Luis,

Unfortunately I have seen this issue as well, and it is not caused by vPoller or Zabbix.

The problem is actually related to vSphere and how to returns the free space, which I believe has been documented somewhere in a KB.

The reason the Zabbix Agent reports correct stats is simply because they check the free space from the OS, and not from the vSphere API.

Unfortunately I cannot do anything about this, because it is a vSphere bug actually.

Regards,
Marin
