### ISSUE TITLE
zabbix simple check command for vm.perf.metric.get

### ISSUE THREAD

**Issue by netscaper71** [dnaeon/py-vpoller#190]
Hi, I have a question about how to format the simple check key for zabbix for Iops monitoring, for example:  vpoller["vm.perf.metric.get", "{$VSPHERE.HOST}", "{HOST.NAME}", "value", "", "", "", "virtualDisk.numberWriteAveraged.number.average", "", ""]

Command bellow gives output but I don't know how to put in zabbix discovered VM drives.
vpoller-client --method vm.perf.metric.get --vsphere-host VCENTERSERVER--name VMNAME --counter virtualDisk.numberReadAveraged.number.average --instance scsi0:0

**Comment by dnaeon** [comment]
You should check the existing discovery items that are already part of the base templates. Following them, should be easy to add custom discovery items as well.
