### ISSUE TITLE
Problem with vpoller on Zabbix 3.X

### ISSUE THREAD

**Issue by takenek** [dnaeon/py-vpoller#193]
Hello
I am not sure, but after upgrade Zabbix to version 3.0  something working wrong.
I report You 08.04.2016 on mail problem with:
vPoller don`t see alert about Less than 20% of free space on HDD,
Now i got another problem and again Zabbix nothing report me:
root@WIZJA2# /usr/local/bin/vpoller-cclient -m vm.get -V vc02.tktelekom.net -n SEOD01.tktelekom.net -p summary.overallStatus
{"msg": "Successfully retrieved object properties", "result": [{"summary.overallStatus": "red", "name": "SEOD01.tktelekom.net"}], "success": 0}

root@WIZJA2:~# /usr/local/bin/vpoller-client -m vm.get -V vc02.tktelekom.net -n SEOD01.tktelekom.net -p summary.overallStatus
{"msg": "Successfully retrieved object properties", "result": [{"summary.overallStatus": "red", "name": "SEOD01.tktelekom.net"}], "success": 0}

In Zabbix i use: Template VMware vSphere Virtual Machine - vPoller Native

Best Regards
Marek

**Comment by dnaeon** [comment]
Hi,

Did you rebuild the vpoller module for Zabbix after the upgrade?

**Comment by takenek** [comment]
Yep i do today again and same effect:
-rwxr-xr-x  1 root   root   14496 cze 16 14:33 vpoller.so

Best Regards

**Comment by dnaeon** [comment]
What about the zabbix logs? Do they show any issues? Please provide as much information as possible, so that I or anyone else can help you.
