### ISSUE TITLE
zabbix-vsphere-import.yaml script stop on error  ERROR - vPoller task failed: {u'msg': u'Cannot collect properties: ', u'success': 1}

### ISSUE THREAD

**Issue by netscaper71** [dnaeon/py-vpoller#195]
Hi, zabbix-vsphere-import.yaml script stop on error  ERROR - vPoller task failed: {u'msg': u'Cannot collect properties: ', u'success': 1} when importing VM's. We have 3 scripts two is working and third not. Third script is for largest vcenter about 1300 vm's. I think that is because he can't collect properties of VM but I can't understand what properties and what VM this is. Are some logs of this process? Where can I look what vm or what properties script cannot read?

Thank You!

**Comment by dnaeon** [comment]
Check the vPoller logs and increase the log level.

**Comment by netscaper71** [comment]
Thank You for the response, but can you exact say what log file we need investigate? /var/log/vpoller.vpoller-worker.log ? What we get of increasing log size?

**Comment by dnaeon** [comment]
@netscaper71, yes the `vpoller-worker.log` should give you more information about the requests which are failing.

If you increase the log level (not the size) to debug, you should get a better idea of what's actually failing.

**Comment by netscaper71** [comment]
hi, we found a problem, our vm's has custom symbols for example ąčęėįšųūž  possible without changing names import them?

**Comment by dnaeon** [comment]
Not really sure. I think you should fix the VM names first, because even if vPoller manages to collect their properties, you will have issues later on with Zabbix, which will not allow you to set these symbols as part of the machine name in Zabbix.

**Comment by netscaper71** [comment]
thank You
