### ISSUE TITLE
Can not get host VM allocated memory.

### ISSUE THREAD

**Issue by leweafan** [dnaeon/py-vpoller#196]
According to vsphere api I should be able to get VM allocated memory using memUsed perf metric which is missing in vpoller. Is there a way to get this metric? 
https://www.vmware.com/support/developer/vc-sdk/visdk400pubs/ReferenceGuide/memory_counters.html

**Comment by dnaeon** [comment]
The provided link is for vSphere 4.x.

The minimum required version for vPoller is at least 5.x and above.

Make sure to check the following tutorial on using performance metrics with vPoller.

- http://vpoller.readthedocs.io/en/latest/examples.html#performance-metrics

Thanks,
Marin
