### ISSUE TITLE
no agents creates zombie processes

### ISSUE THREAD

**Issue by jabalv** [dnaeon/py-vpoller#198]
when there is no agents in sql lite db, starting vpoller-worker creates zombie proccesses. I suppose workers and sockets should be killed - close_sockets()/stop_workers() or so in create_agents() on failure? hmm... I need more time to investigate, but ...

**Comment by dnaeon** [comment]
I'll check this when I have some spare time, been sick these days.

**Comment by dnaeon** [comment]
This is a really old one and should be fixed long time ago, so closing it.
