### ISSUE TITLE
Zabbix Import Addition

### ISSUE THREAD

**Issue by pmelse** [dnaeon/py-vpoller#199]
Hi Everyone,

I'm not certain if this something people would like (or if my code is worthy of a pull request), but I've extended the zabbix-vsphere-import with the following features:

-Skip Processing hosts via regular expressions (against hostname). (useful if you have things like view pools, linked clones, or test hosts which don't require monitoring. This is also useful for removing all vpoller discovered VM's using /.*/ along with the -d option.

-OS template support for Windows, Linux (based on the VM's GuestOsIdentifier )
-Additional Host Group support (also determined by GuestOSIdentifier)

additional keys in yaml (for vsphere_object_vm):
wintemplate / lintemplate (optional) | specify which template based on OS to add to the host
wingroup / lingroup  (optional) | specify which additional host group (based on OS) to add to the host.

Since this is only really useful for machines also monitoring with zabbix_agent, would adding a second example script be the way to go here?

Resources:
https://www.vmware.com/support/developer/converter-sdk/conv55_apireference/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html

**Comment by dnaeon** [comment]
Hey,

I think these are nice additions! Please consider submitting pull requests for each of these enhancements.

**Comment by dnaeon** [comment]
I'll close this issue, since we can track progress of adding these features in the pull requests.
