### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by indreek** [dnaeon/py-vpoller#200]
Hi!

What method and property should i use to get snapshot information?

**Comment by dnaeon** [comment]
Currently vPoller does not have any methods for snapshots implemented.

We can certainly add though. What info would you need to get about snapshots?

These are the snapshots properties we can retrieve for a VirtualMachine.

http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.SnapshotInfo.html

**Comment by indreek** [comment]
Finally i would like to see with zabbix if some backups are older than x period or bigger than x.

Indrek

**Comment by dnaeon** [comment]
The `vm.snapshot.get` method has been added to version 0.6.3. Please update your vPoller.

Here's an example usage of this method.

```bash
$ vpoller-client --method vm.snapshot.get --vsphere-host <vcenter> --name <virtualmachine>
```

Which for my VM with only a single snapshot returns this result.

```json
{
  "success": 0,
  "msg": "Successfully retrieved snapshots",
  "result": [
    {
      "state": "poweredOff",
      "name": "test-snapshot-1",
      "createTime": "2016-07-04 15:18:03.067982+00:00",
      "description": "",
      "quiesced": "False",
      "id": 3
    }
  ]
}
```

As for using this method in Zabbix, you can check how the discovery and prototype items for `Datacenter Alarms` are created, so you can create your items in a similar way.

**Comment by Bonn93** [comment]
So would this make it possible to find aged or nested snapshots - perhaps over x,y and z duration as a item in the templates?

**Comment by dnaeon** [comment]
@blackcobra1973, yes should be possible. Just make sure to configure your triggers.
