### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by indreek** [dnaeon/py-vpoller#204]
Hi

I have a question about manual. 
http://vpoller.readthedocs.io/en/latest/vpoller-zabbix.html#why-use-vpoller-with-zabbix-and-not-just-use-stock-zabbix-for-vmware-monitoring
In manual it says:
Here is one example that uses zabbix_get(8) in order check the power state of VM using the vpoller[*] key.
$ zabbix_get -s 127.0.0.1 -p 10050 -k "vpoller[vm.get, vc01.example.org, ns01.example.org, runtime.powerState]"

my system is 
vmware host:

- esxi host name: esxi01.domain.local
- esxi ip: 192.168.100.100

virtual machine

- vm name: vm01
- vm dns name: vm01.domain.local
- vm ip: 192.168.101.100

Zabbix server

- zabbix dns name: zabbix.domain.local
- zabbix ip: 192.168.101.99

What would be commands if i like to receive information about a) virtual machine b) about esxi host?

**Comment by indreek** [comment]
Figured out that in /etc/zabbix/zabbix_agentd.conf you need to enable access from 127.0.0.1. 

> Server = zabbix.domain.local,127.0.0.1

Now i get error 
zabbix_get -s 127.0.1.1 -p 10050 -k 'vpoller["event.latest", "esxi01.domain.local", "null", "event", "null"]'
ZBX_NOTSUPPORTED: Unsupported item key.

Still now working, but new error. In zabbix i see values but i cannot get them from command line.

**Comment by dnaeon** [comment]
Do you see any errors in the vpoller-worker and zabbix logs?

**Comment by indreek** [comment]
Nope

**Comment by dnaeon** [comment]
Would be better if you can provide actual logs, otherwise I cannot really tell what could be the issue.

**Comment by indreek** [comment]
There is nothing in logs. Absolutely zero. Zabbix_server, zabbix_agent, vpoller-worker have nothing about vpoller. 

Im running tail -f on separate session with all those log files.

**Comment by indreek** [comment]
But zabbix itself is getting values. I just cannot execute command line commands.

**Comment by indreek** [comment]
![image](https://cloud.githubusercontent.com/assets/5476647/17050807/a4f0ad50-4ffd-11e6-8a4a-1481e95fd161.png)
vs 
![image](https://cloud.githubusercontent.com/assets/5476647/17050819/ba7f06a8-4ffd-11e6-9e36-43a3aa9d1ea1.png)


and nothing in logs.

**Comment by dnaeon** [comment]
You may need to enable debug logs and see what's happening on the zabbix side when you request this item. Currently I'm not able to test that myself, but hope to get some spare time these days and see if I can re-produce it.

**Comment by indreek** [comment]
I fixed it!

It doesn't say in manual that vpoller.so needs to be loaded in zabbix_agentd.conf also. After adding 
LoadModulePath=/usr/local/lib/zabbix
LoadModule=vpoller.so
everything works fine now.

**Comment by dnaeon** [comment]
Well, yes.. you need to enable the module for each service you need the module - zabbix server, agent or proxy.. Could be that the documentation was not clear enough about that point.

Please consider sending a PR to update the documentation in order to clarify that point.
