### ISSUE TITLE
Cannot get some cluster properties

### ISSUE THREAD

**Issue by hunbalazs** [dnaeon/py-vpoller#206]
When I get cluster properties, some of the just return: {"msg": "Cannot collect properties: ", "success": 1}
I looked behind the problem and found that only properties belongs to ClusterComputeResourceSummary cannot be obtained (ComputeResourceSummary properties are returned OK).

**Comment by dnaeon** [comment]
What is the vSphere version that you are using?

**Comment by hunbalazs** [comment]
VMware vCenter Server 6.0.0 build-3339083
vpoller version 0.6.3

**Comment by hunbalazs** [comment]
@dnaeon Were you able to reproduce the issue?

**Comment by dnaeon** [comment]
Sorry for the delay, buut I haven't found time to check this one. Been busy at work, and then with family stuff, so didn't really had some spare time to look into this one.

**Comment by dnaeon** [comment]
Latest version of vPoller supports retrieving all properties from vSphere.
