### ISSUE TITLE
vpoller module loaded but "item key not supported" for discovery items

### ISSUE THREAD

**Issue by DRVTiny** [dnaeon/py-vpoller#210]
Good time of day!
I have compiled vpoller.so for zabbix 3.0.7 It is loaded in server properly, vpoller tells about succesfull loading in zabbix_server.log file. 
Than i've loaded this module into zabbix_agentd too and i can request discovery items like vpoller["vm.discover"] and so - it seems all vpoller components configured properly.
But when i use discover keys as "Simple checks" on the server side - it always returns as "Unsupported item key". I have absolutely the same Zabbix configuration in another datacenter - and there vpoller.so works well in zabbix_server, but for some strange reasons not work at all in zabbix_agentd running on the same server as the zabbix_server does.
So... maybe i can attach vpoller.so to zabbix_server or to zabbix_agentd, but not to both?
How to see requests/answers to/from vpoller.so?

**Comment by DRVTiny** [comment]
>I have absolutely the same Zabbix configuration in another datacenter - and there vpoller.so works well in zabbix_server, but for some strange reasons not work at all in zabbix_agentd running on the same server as the zabbix_server does

Vpoller keys returns "empty" strings (maybe "\n", not "").

```
[a.konovalov@my-zbx-server Perl5]$ zabbix_get -s my-zbx-server.my-domain -k 'vpoller["vm.discover", "my-vc-server.my-domain", "null", "name", "null"]'

[a.konovalov@my-zbx-server Perl5]$
```

**Comment by DRVTiny** [comment]
Logs collected at the same time from zabbix_server and from zabbix_agent: attached

[vpoller_module.txt](https://github.com/dnaeon/py-vpoller/files/744802/vpoller_module.txt)

**Comment by dnaeon** [comment]
Hi,

I haven't tested vPoller much with Zabbix 3.x, and it may take me a while to get a Zabbix 3.x environment, where I can test things.

Hopefully someone from the other users can comment on their success with Zabbix 3.

**Comment by ashishchakrabortty** [comment]
Hi Dnaeon,

Did you have any updates in this case?

**Comment by dnaeon** [comment]
@ashishchakrabortty No, I haven't had a chance to look into this one as I'm quite busy with other projects these days.

It would be great if someone is willing to step up and volunteer help maintaining this project.

**Comment by dnaeon** [comment]
Should be fixed by now as reported by other users who already use vPoller with Zabbix 3.x.

If you still experience this issue, please feel free to re-open.
