### ISSUE TITLE
[question] - vCenter 6.5 

### ISSUE THREAD

**Issue by Bonn93** [dnaeon/py-vpoller#211]
Hello,  just a question if any testing has occurred with vCenter 6.5. I'm considering an update to this for various reasons but don't want our vPoller to be stuck in the water.

**Comment by dnaeon** [comment]
Hey @Bonn93 

vPoller should work just fine with vSphere 6.x. I have heard of people running it in production with vCenter 6.5 as well.

I'd suggest that you setup a test environment and do any testing there first, just to make sure everything is going to work out just fine.
