### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by Emmanux** [dnaeon/py-vpoller#214]
The example yaml is wrong:
https://github.com/dnaeon/py-vpoller/blob/master/docs/vpoller-zabbix.rst

Please, fix indentation. I copied from documentation, and it didn't work. Painful troubleshooting. I trusted the documentation.

**Comment by dnaeon** [comment]
Please consider submitting a PR with the fix.

**Comment by rockaut** [comment]
Tried it. Worked for me. Also online yaml linter states no problems?
Maybe just a problem with copy-paste and browser/editor character encoding?

@Emmanux you may also just fetch the file with wget from https://raw.githubusercontent.com/dnaeon/py-vpoller/master/extra/zabbix/vsphere-import/zabbix-vsphere-import.yaml or even better clone the repository and copy the file.

**Comment by Emmanux** [comment]
I made a pull request.
https://github.com/dnaeon/py-vpoller/pull/231/commits/8d668a5e6265a085c2d7140fd98de36cdc934933
