### ISSUE TITLE
vpoller.helpers.csvhelper does not seem to be working

### ISSUE THREAD

**Issue by andrea-82** [dnaeon/py-vpoller#216]
Hi,

Running something like:
`vpoller-client -H vpoller.helpers.csvhelper -m vm.discover -V my-vc.company.int -p runtime.powerState`
returns the correct data but in a JSON format, rather than CSV.

Please let me know know if I am missing something or it's a bug.

Regards,
Andrea

**Comment by dnaeon** [comment]
Hi,


It's been a while since I've updated the CSV helpers, so they could be
broken at the moment. I cannot test this myself at the moment, but you
could use the returned JSON to construct a CSV if needed.

**Comment by andrea-82** [comment]
OK.
I resolved using "jq".

Thank you!
Andrea

**Comment by mikerosile** [comment]
@andrea-82 Could you post a working example using 'jq' ?

**Comment by andrea-82** [comment]
Hi @mikerosile,
I'm not using this anymore but, looking at my notes, I used jq to modify the vpoller output to make it csv valid.

For example, in this case I wanted to know the VM power state so I did:
vpoller-client --method vm.discover --vsphere-host <vcenter_IP/hostname> --properties runtime.powerState | jq '.result | map([.name] | join(", ")) | join("\n")' > powerState.csv

Hope it helps.
Andrea

**Comment by mikerosile** [comment]
Thank you, much appreciated!
