### ISSUE TITLE
zabbix-vsphere-import duplicate hosts

### ISSUE THREAD

**Issue by zuhairraza** [dnaeon/py-vpoller#218]
Hello
Can we have Vsphere.Hostname as prefix in name of Imported VMs? 
I have couple of servers with same VM names and zabbix doesn't allow same hostname to be added again.

**Comment by dnaeon** [comment]
In theory - yes, you can do that. In practice this would not work well, because the Zabbix templates already use the `hostname` of the VM, so the `prefix` does not tell anything to vPoller when a new request comes in, since it will not be able to find the vSphere object.

**Comment by zuhairraza** [comment]
which zabbix template?

**Comment by dnaeon** [comment]
Closing this one. If you really need this, please consider opening a PR, so we can follow up there.
