### ISSUE TITLE
zabbix-vsphere-import requires Super Admin permissions

### ISSUE THREAD

**Issue by emmnx** [dnaeon/py-vpoller#219]
Please, make an option to drop that host group creation feature. It's really messy, I can't decide the name that my customers give to their clusters. It rapidly becomes a mess. 

Besides that, I don't want to let Super Admin passwords in my customers proxies, it's just... no.

**Comment by dnaeon** [comment]
Well, you only need a user that can create hosts in Zabbix, so there is no strict requirement for a super-admin user at all.

**Comment by emmnx** [comment]
Host group, not host.
