### ISSUE TITLE
[zbx-helper]: Do not know how to process vm.guest.net.get method

### ISSUE THREAD

**Issue by Slper** [dnaeon/py-vpoller#220]
I try to create customize item on template "Template VMware vSphere Virtual Machine - vPoller Native" To find ip address of vm guest and i got error returned as below.

[zbx-helper]: Do not know how to process vm.guest.net.get method

My item vpoller key as shown

vpoller["vm.guest.net.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "ipAddress", ""]

I can get ip address from command line "vpoller-client -m vm.guest.net.get -V <VC_IP> --name <Guest_name> --properties ipAddress"

Not sure what did i do wrong please help me.

**Comment by dnaeon** [comment]
This file needs to be updated and have the method name included 

https://github.com/dnaeon/py-vpoller/blob/master/src/vpoller/helpers/zabbix.py#L55

Please consider updating the file and submitting a PR for it.

**Comment by Slper** [comment]
hi,

I've updated zabbix.py as below

`  self.methods = {
            'about': self.zabbix_item_value,
            'event.latest': self.zabbix_item_value,
            'session.get': self.zabbix_lld_data,
            'datacenter.discover': self.zabbix_lld_data,
            'datacenter.get': self.zabbix_item_value,
            'datacenter.alarm.get': self.zabbix_lld_data,
            'datacenter.perf.metric.get': self.zabbix_item_value,
            'datacenter.perf.metric.info': self.zabbix_lld_data,
            'cluster.alarm.get': self.zabbix_lld_data,
            'cluster.discover': self.zabbix_lld_data,
            'cluster.get': self.zabbix_item_value,
            'cluster.perf.metric.get': self.zabbix_item_value,
            'cluster.perf.metric.info': self.zabbix_lld_data,
            'host.alarm.get': self.zabbix_lld_data,
            'host.discover': self.zabbix_lld_data,
            'host.get': self.zabbix_item_value,
            'host.vm.get': self.zabbix_lld_data,
            'host.datastore.get': self.zabbix_lld_data,
            'host.cluster.get': self.zabbix_item_value,
            'host.perf.metric.get': self.zabbix_item_value,
            'host.perf.metric.info': self.zabbix_lld_data,
            'vm.alarm.get': self.zabbix_lld_data,
            'vm.discover': self.zabbix_lld_data,
            'vm.get': self.zabbix_item_value,
            'vm.guest.net.get': self.zabbix_item_value,
            'vm.datastore.get': self.zabbix_lld_data,
            'vm.disk.discover': self.zabbix_vm_disk_discover,
            'vm.disk.get': self.zabbix_vm_disk_get,
            'vm.host.get': self.zabbix_item_value,
            'vm.process.get': self.zabbix_vm_process_get,
            'vm.cpu.usage.percent': self.zabbix_item_value,
            'vm.perf.metric.get': self.zabbix_item_value,
            'vm.perf.metric.info': self.zabbix_lld_data,
            'vm.snapshot.get': self.zabbix_lld_data,
            'datastore.alarm.get': self.zabbix_lld_data,
            'datastore.discover': self.zabbix_lld_data,
            'datastore.get': self.zabbix_item_value,
            'datastore.host.get': self.zabbix_lld_data,
            'datastore.vm.get': self.zabbix_lld_data,
            'datastore.perf.metric.get': self.zabbix_item_value,
            'datastore.perf.metric.info': self.zabbix_lld_data,
            'vsan.health.get': self.zabbix_item_value,
        }`

i added vm.guest.net.get into self.methods. however still unable to get data from vpoller as error shown "[zbx-helper]: Do not know how to process vm.guest.net.get method" 

BTW, I've restarted vpoller after change configuration.

**Comment by Slper** [comment]
update...

some of server got this error "Task vm.guest.net.get failed"

**Comment by dnaeon** [comment]
Please show the logs when you request the `vm.guest.net.get` method.

**Comment by Slper** [comment]
[root@Test-BJVZabbix01 log]# grep vm.guest.net.nget vpoller-worker.log
[root@Test-BJVZabbix01 log]# grep vm.guest.net.get vpoller-worker.log
[2017-10-31 16:42:41,333 - WARNING/VPollerWorker-6] [zbx-helper]: Do not know how to process vm.guest.net.get method
[2017-10-31 16:44:39,523 - WARNING/VPollerWorker-7] [zbx-helper]: Do not know how to process vm.guest.net.get method
[2017-10-31 16:45:33,136 - WARNING/VPollerWorker-4] [zbx-helper]: Do not know how to process vm.guest.net.get method
[2017-10-31 16:45:53,108 - WARNING/VPollerWorker-7] [zbx-helper]: Do not know how to process vm.guest.net.get method
[2017-10-31 16:46:34,594 - WARNING/VPollerWorker-3] [zbx-helper]: Do not know how to process vm.guest.net.get method
[2017-10-31 16:47:08,228 - WARNING/VPollerWorker-5] [zbx-helper]: Do not know how to process vm.guest.net.get method
[2017-10-31 16:48:22,649 - WARNING/VPollerWorker-2] [zbx-helper]: Do not know how to process vm.guest.net.get method
[2017-10-31 17:01:09,583 - WARNING/VPollerWorker-1] [zbx-helper]: Do not know how to process vm.guest.net.get method

**Comment by dnaeon** [comment]
Did you run 'python setup.py install' after the update?

**Comment by Slper** [comment]
Dear Dnaeon,

yes i didn'y run command to install after change config

however, after i run installed command i got error 


2017-11-01 11:59:07 | {"msg": "Cannot send result: unicode/str objects only", "success": 1}
-- | --

this is how i set my parameter

vpoller["vm.guest.net.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "ipAddress", ""]

**Comment by Slper** [comment]
Hi Please help me..

**Comment by dnaeon** [comment]
Hi,

I've been too busy at work these days. Will try to look into this one soon.

**Comment by Slper** [comment]
Thanks :)

**Comment by Slper** [comment]
FYI i just want to get IP address of vm guest. if there are another way, Please suggest.

**Comment by dnaeon** [comment]
I've just submitted fd6aad06a14caa4583f501fc7c173600247e9bcc which should fix this for you.

Here's how to get the latest code.

```bash
git clone https://github.com/dnaeon/py-vpoller
cd py-vpoller
python setup.py install
```

Then start your proxy and workers as usual.

Here's an example request that you could use with the zabbix helper.

```bash
vpoller-client --method vm.guest.net.get --vsphere-host <vcenter> --name <vm-name> --properties network,connected,macAddress,ipAddress --helper vpoller.helpers.zabbix | jq '.'
```

**Comment by Slper** [comment]
Hi,

I've updated and it work perfectly. :)

I got returned result like this

{"data": [{"{#VSPHERE.VM.NETWORK}": "VM Network", "{#VSPHERE.VM.IPADDRESS}": ["fe80::303a:e0b:d79e:a451", "172.30.19.42"]}]}

May i ask? if i want only ipaddress, how do i config my item on zabbix. Currently I put it this way.

vpoller["vm.guest.net.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "ipAddress", "null"]

**Comment by Slper** [comment]
as I know I can put it in discovery list and create prototype item by using value {#VSPHERE.VM.IPADDRESS} but prototype item cannot put into inventory for hosts. if I want ipaddress as inventory for host, what should i do?

**Comment by dnaeon** [comment]
Please check the existing template files, which should have similar items.
