### ISSUE TITLE
Could 2 vpoller monitor 1 vcenter together?

### ISSUE THREAD

**Issue by ethan-peng** [dnaeon/py-vpoller#221]
Hi,
I user vpoller and zabbix to monitor my vcenter and it works well.
I built a new test environment recently.
We want to run both these 2 vpoller to monitor vcenter together.
But they could'nt run at the same time.

I deploy the vpoller according to this website http://vpoller.readthedocs.io/en/latest/vpoller-zabbix.html
Could I make any other configuration?
Thanks.

**Comment by dnaeon** [comment]
Yes, you can monitor any number of vcenters.

Just increase the number of workers and create new agents to use them.
