### ISSUE TITLE
Simple Check =  Item Not Supported

### ISSUE THREAD

**Issue by diegoarioza** [dnaeon/py-vpoller#222]
Hello, I configured vpoller following the manual, following the details, but applying the default template, all items are not supported in zabbix, running the command using zabbix_get I have the correct return, then I made a test, I changed the template items of " simple check "for" zabbix agen "and everything started collecting normally, is there anything wrong I've done?

**Comment by rockaut** [comment]
You are right. If you use the zabbix agent with the vpoller helper you have to switch the type of check.
It seams the templates are meant for the zabbix server or proxy where the vpoller helper would use the simple check.

**Comment by dnaeon** [comment]
Please feel free to send a PR for updating the documentation, if you think it is not in a good shape.

You haven't mentioned which templates you've used, so it could be that you mixed native checks with external ones.
