### ISSUE TITLE
Powered off VMs and vm.perf.metric

### ISSUE THREAD

**Issue by Satei** [dnaeon/py-vpoller#234]
Hello

Is there a way to get the zabbix-vsphere-import script to delete VMs there are powered off?
My reason is, powered off VMs don't get vm.perf.metric.get and so every off VM gets 2 missing items.

Regards
Bodo

**Comment by dnaeon** [comment]
The script only removes VMs if they are no longer present in vcenter.

I’m quite busy these days at work, so not sure when I will have time to check this, but if anyone wants to pick this up that would be great.

**Comment by dnaeon** [comment]
Another way to solve this is to add the VMs in question to the `ignore list`.

Check the example config file.

* https://github.com/dnaeon/py-vpoller/blob/master/extra/zabbix/vsphere-import/zabbix-vsphere-import.yaml#L43

**Comment by Satei** [comment]
That didn't solve the problem because the vm is in zabbix.
The only "solution" is to manually delete the vm in zabbix but that's a little bit annoying so I hoped for a better solution.

**Comment by dnaeon** [comment]
Can you please try out the following patch?

Make sure to run the Zabbix import script in dry-run mode first in order to verify the correct behaviour.

```diff
diff --git a/extra/zabbix/vsphere-import/zabbix-vsphere-import b/extra/zabbix/vsphere-import/zabbix-vsphere-import
index d19156b..b7e3e8d 100755
--- a/extra/zabbix/vsphere-import/zabbix-vsphere-import
+++ b/extra/zabbix/vsphere-import/zabbix-vsphere-import
@@ -471,9 +471,11 @@ class ZabbixVSphere(object):
 
         msg = {
             'method': 'vm.discover',
-            'hostname': self.options['vsphere']['hostname']
+            'hostname': self.options['vsphere']['hostname'],
+            'properties': 'runtime.powerState',
         }
         vpoller_data = self._call_vpoller_task(msg=msg)
+
         # regex of all vm names where logging is not desired.                                       
         # Get hosts options (templates, groups, macros, ignore_vm(optional))
         host_options = self._get_zabbix_host_options('vsphere_object_vm')
@@ -482,13 +484,21 @@ class ZabbixVSphere(object):
         for regex in self.vsphere_exclude_list:
             regex_list.append(re.compile(regex))
         vmreal = []
-        for h in vpoller_data:
-        # Remove hosts on the ignore list (ignore_vm key/values in config file.)                                
-            if not any(regex.match(h[u'name']) for regex in regex_list):                                         
-                vmreal.append(h['name'])                                                                          
-        self.vsphere_vms = vmreal                                                                                 
-        missing_hosts = set(self.vsphere_vms) - set(zabbix_hosts)                                                 
-  
+
+        vsphere_vms = []
+        skip_vm_in_powerstate = host_options.get('skip_vm_in_powerstate')
+        if skip_vm_in_powerstate:
+            vsphere_vms = [h for h in vpoller_data if h['runtime.powerState'] not in skip_vm_in_powerstate]
+        else:
+            vsphere_vms = vpoller_data
+
+        for h in vsphere_vms:
+            # Remove hosts on the ignore list (ignore_vm key/values in config file.)
+            if not any(regex.match(h[u'name']) for regex in regex_list):
+                vmreal.append(h['name'])
+        self.vsphere_vms = vmreal
+        missing_hosts = set(self.vsphere_vms) - set(zabbix_hosts)
+
         if not missing_hosts:
             logging.info(
                 '[VirtualMachine@%s] Objects are in sync with Zabbix',
diff --git a/extra/zabbix/vsphere-import/zabbix-vsphere-import.yaml b/extra/zabbix/vsphere-import/zabbix-vsphere-import.yaml
index 0416a7d..b13a269 100644
--- a/extra/zabbix/vsphere-import/zabbix-vsphere-import.yaml
+++ b/extra/zabbix/vsphere-import/zabbix-vsphere-import.yaml
@@ -40,6 +40,9 @@ zabbix:
       - Hypervisors
 
   vsphere_object_vm:
+    skip_vm_in_powerstate: # Skip VMs in the following power states
+      - poweredOff
+      - suspended
     ignore_vm: # any vsphere VM name matching the following regex patterns
                # will not be imported, use .* with the -d option to remove all 
                # vpoller-imported hosts
```

**Comment by dnaeon** [comment]
Oops, the `properties` field is a list, I've fixed that in the initial diff above.

Please try again and let me know how it goes.

Thanks,
Marin

**Comment by Satei** [comment]
The script runs, but it does not what I expect.
It gets the VM who is PoweredOff:
[2018-03-28 12:53:30,909] - INFO - [VirtualMachine@VCSA] VM 'Off-VM' is not powered on, will not be imported
But it does not delete the VM object in Zabbix.

**Comment by dnaeon** [comment]
Did you update the `yaml` file to include the `skip_vm_in_powerstate` setting as well?

**Comment by Satei** [comment]
Yes:
  vsphere_object_vm:
    proxy: ZPROXY
    skip_vm_in_powerstate: # Skip VMs in the following power states
      - poweredOff
      - suspended
    ignore_vm: # any vsphere VM name matching the following regex patterns
               # will not be imported, use .* with the -d option to remove all
               # vpoller-imported hosts
     - ^TESTVM
    templates:
      - Template VMware vSphere Virtual Machine - vPoller Native
    macros:
      VSPHERE.HOST: VCSA
    groups:
      - Virtual Machines

**Comment by dnaeon** [comment]
I've just pushed a fix, please grab the latest version of the script from the Git repo. Should be good now. 

Let me know how it goes.

**Comment by Satei** [comment]
The last change was for docker. No changes on the script or yaml.

**Comment by dnaeon** [comment]
Damn, I forgot to push :)

The change is now in the repo, please test with it.

**Comment by mikefarace** [comment]
Hello, related to this, can you skip all VM's that are in a specific folder in Vsphere?  we have a folder where archived and to be deleted VM's are put, which don't need to be monitored.
