### ISSUE TITLE
zabbix-vsphere-import - Zabbix SSL connection

### ISSUE THREAD

**Issue by rockaut** [dnaeon/py-vpoller#240]
Would it be possible to get an zabbix-vsphere-import option for ignoring SSL verification on zabbix connect?

**Comment by dnaeon** [comment]
Hey @rockaut 

Sure, we can have this one. Do you mind submitting a PR for this? 

Some time ago I've blogged about it, which is more or less this thing.

http://dnaeon.github.io/disable-python-ssl-verification/

Will need to test this though.

**Comment by rockaut** [comment]
Will have a look over weekend.
I'm currently implementing vPoller through docker in Zabbix and have some more findings. Will try to contribute as much as i can.

**Comment by rockaut** [comment]
Resolved with workarounds
