### ISSUE TITLE
[zbx-helper]: Do not know how to process resource.pool.get method

### ISSUE THREAD

**Issue by ethan-peng** [dnaeon/py-vpoller#247]
Hi dnaeon,

The vpoller version that I'm using is 0.6.3.
I tried to monitor resource pool recently

The command line test result is as following.
`# vpoller-client --method resource.pool.get --vsphere-host  192.168.9.9 --name Resource_poll_01 --properties runtime.overallStatus`
`{"msg": "Successfully retrieved object properties", "result": [{"name": "Resource_poll_01", "runtime.overallStatus": "green"}], "success": 0}`

Zabbix key is like this,
`vpoller["resource.pool.get", "{$VSPHERE.HOST}", "{HOST.HOST}", "runtime.overallStatus", "null"]`

But I got some warning messages
`[2018-05-22 16:54:44,977 - WARNING/VPollerWorker-7] [zbx-helper]: Do not know how to process resource.pool.get method`
`[2018-05-22 16:54:46,176 - WARNING/VPollerWorker-2] [zbx-helper]: Do not know how to process resource.pool.get method`

And I've read issue #220 and checked the zabbix.py that I used and your git version (https://github.com/dnaeon/py-vpoller/blob/master/src/vpoller/helpers/zabbix.py#L55)
resource.pool.get method is not in either of them.

Is it not supported for now ? Or I'm using it in a wrong way ?

Looking forward to your reply

Many thanks.

**Comment by dnaeon** [comment]
Hi,

The method needs to be added to the Zabbix helper module.

I will check this later today and let you know when it’s done.

Thanks,
Marin

**Comment by dnaeon** [comment]
Can you try the latest version from the Git repo and let me know how it goes?

The vPoller version you should have once installed from the latest Git repo should be v0.7.1

**Comment by ethan-peng** [comment]
Hi Marin,

I tried the latest version. It works. Thanks.
