### ISSUE TITLE
 vpoller-client on zabbix 4.2 problem

### ISSUE THREAD

**Issue by horityhu** [dnaeon/py-vpoller#269]
I had install the env and the vpoller on my server.
as below error:

[root@zabbix4-server ~]# vpoller-client -m host.discover -V 10.0.0.52
Traceback (most recent call last):
  File "/usr/bin/vpoller-client", line 4, in <module>
    __import__('pkg_resources').run_script('vpoller==0.7.3', 'vpoller-client')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/vpoller-client' not found in metadata at '/usr/lib/python2.7/site-packages/vpoller-0.7.3-py2.7.egg-info'
[root@zabbix4-server ~]# 
Socket error Event: 32 Error: 10053.

**Comment by dnaeon** [comment]
It seems something is wrong with the way you installed it.

Also please use Python 3, as v2 will be EOL soon.

**Comment by horityhu** [comment]
hello

发自我的iPhone

> 在 2019年11月12日，下午2:31，Marin Atanasov Nikolov <notifications@github.com> 写道：
> 
> ﻿It seems something is wrong with the way you installed it.
> 
> Also please use Python 3, as v2 will be EOL soon.
>

**Comment by horityhu** [comment]
I had reinstall the zabbix 4.2 env.
python 2.7
and run the "$pip install vpoller"
the install process as below:

`[root@zabbix4-server ~]# pip install vpoller
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting vpoller
  Downloading https://files.pythonhosted.org/packages/fa/77/f17f025706f92f9ce87c4af4429db8cb4651f5eeed0ff048300755eb4d9c/vpoller-0.7.3.tar.gz
Collecting pyzmq>=14.3.1 (from vpoller)
  Downloading https://files.pythonhosted.org/packages/c8/f8/73c259238e6ec5afbede83a3f4e75f57228171109aafa4aa1b8c33e09778/pyzmq-18.1.1-cp27-cp27mu-manylinux1_x86_64.whl (1.0MB)
     |████████████████████████████████| 1.0MB 10kB/s 
Collecting docopt>=0.6.2 (from vpoller)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting pyvmomi>=6.0.0 (from vpoller)
  Downloading https://files.pythonhosted.org/packages/eb/87/ebf153a3aafdac7c54c5578b6240d7930a8c0a1a21bdd98d271fd131673c/pyvmomi-6.7.3.tar.gz (576kB)
     |████████████████████████████████| 583kB 12kB/s 
Collecting vconnector>=0.5.0 (from vpoller)
  Downloading https://files.pythonhosted.org/packages/22/9e/52cae036555ec85f0508e2d294b6bf491e496c3463784853d6f88a905662/vconnector-0.6.0.tar.gz
Requirement already satisfied: requests>=2.3.0 in /usr/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller) (2.22.0)
Requirement already satisfied: six>=1.7.3 in /usr/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller) (1.12.0)
Collecting tabulate>=0.8.3 (from vconnector>=0.5.0->vpoller)
  Downloading https://files.pythonhosted.org/packages/66/d4/977fdd5186b7cdbb7c43a7aac7c5e4e0337a84cb802e154616f3cfc84563/tabulate-0.8.5.tar.gz (45kB)
     |████████████████████████████████| 51kB 11kB/s 
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi>=6.0.0->vpoller) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi>=6.0.0->vpoller) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi>=6.0.0->vpoller) (1.25.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi>=6.0.0->vpoller) (2019.6.16)
Installing collected packages: pyzmq, docopt, pyvmomi, tabulate, vconnector, vpoller
  Running setup.py install for docopt ... done
  Running setup.py install for pyvmomi ... done
  Running setup.py install for tabulate ... done
  Running setup.py install for vconnector ... done
  Running setup.py install for vpoller ... done
Successfully installed docopt-0.6.2 pyvmomi-6.7.3 pyzmq-18.1.1 tabulate-0.8.5 vconnector-0.6.0 vpoller-0.7.3
WARNING: You are using pip version 19.2.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

it sames like successful.

**Comment by horityhu** [comment]
> I had reinstall the zabbix 4.2 env.
> python 2.7
> and run the "$pip install vpoller"
> the install process as below:
> 
> `[root@zabbix4-server ~]# pip install vpoller DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support Collecting vpoller Downloading https://files.pythonhosted.org/packages/fa/77/f17f025706f92f9ce87c4af4429db8cb4651f5eeed0ff048300755eb4d9c/vpoller-0.7.3.tar.gz Collecting pyzmq>=14.3.1 (from vpoller) Downloading https://files.pythonhosted.org/packages/c8/f8/73c259238e6ec5afbede83a3f4e75f57228171109aafa4aa1b8c33e09778/pyzmq-18.1.1-cp27-cp27mu-manylinux1_x86_64.whl (1.0MB) |████████████████████████████████| 1.0MB 10kB/s Collecting docopt>=0.6.2 (from vpoller) Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz Collecting pyvmomi>=6.0.0 (from vpoller) Downloading https://files.pythonhosted.org/packages/eb/87/ebf153a3aafdac7c54c5578b6240d7930a8c0a1a21bdd98d271fd131673c/pyvmomi-6.7.3.tar.gz (576kB) |████████████████████████████████| 583kB 12kB/s Collecting vconnector>=0.5.0 (from vpoller) Downloading https://files.pythonhosted.org/packages/22/9e/52cae036555ec85f0508e2d294b6bf491e496c3463784853d6f88a905662/vconnector-0.6.0.tar.gz Requirement already satisfied: requests>=2.3.0 in /usr/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller) (2.22.0) Requirement already satisfied: six>=1.7.3 in /usr/lib/python2.7/site-packages (from pyvmomi>=6.0.0->vpoller) (1.12.0) Collecting tabulate>=0.8.3 (from vconnector>=0.5.0->vpoller) Downloading https://files.pythonhosted.org/packages/66/d4/977fdd5186b7cdbb7c43a7aac7c5e4e0337a84cb802e154616f3cfc84563/tabulate-0.8.5.tar.gz (45kB) |████████████████████████████████| 51kB 11kB/s Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi>=6.0.0->vpoller) (3.0.4) Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi>=6.0.0->vpoller) (2.8) Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi>=6.0.0->vpoller) (1.25.3) Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi>=6.0.0->vpoller) (2019.6.16) Installing collected packages: pyzmq, docopt, pyvmomi, tabulate, vconnector, vpoller Running setup.py install for docopt ... done Running setup.py install for pyvmomi ... done Running setup.py install for tabulate ... done Running setup.py install for vconnector ... done Running setup.py install for vpoller ... done Successfully installed docopt-0.6.2 pyvmomi-6.7.3 pyzmq-18.1.1 tabulate-0.8.5 vconnector-0.6.0 vpoller-0.7.3 WARNING: You are using pip version 19.2.1, however version 19.3.1 is available. You should consider upgrading via the 'pip install --upgrade pip' command. `
> 
> it sames like successful.

but I can not find"/etc/vpoller/vpoller.conf"

**Comment by dnaeon** [comment]
Please use python 3 and post the logs containing errors.

**Comment by horityhu** [comment]
I had reinstall the zabbix env again.
env is:
1.python 3.7.5
2.pip19.2.3
I had run the "pip install vpoller"
where is the vpoller conf file?

`[root@zabbix4-server bin]# python3 -V
Python 3.7.5
[root@zabbix4-server bin]# pip3 -V
pip 19.2.3 from /usr/local/python3/lib/python3.7/site-packages/pip (python 3.7)
[root@zabbix4-server bin]# pip3 install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
     |████████████████████████████████| 1.4MB 12kB/s 
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.3.1
[root@zabbix4-server bin]# pip3 install vpoller
Collecting vpoller
  Downloading https://files.pythonhosted.org/packages/fa/77/f17f025706f92f9ce87c4af4429db8cb4651f5eeed0ff048300755eb4d9c/vpoller-0.7.3.tar.gz
Collecting pyzmq>=14.3.1
  Downloading https://files.pythonhosted.org/packages/bf/dd/547bee2080beefe6546c332422cb0f189b3cd71cfff048146cd9ac3751cc/pyzmq-18.1.1-cp37-cp37m-manylinux1_x86_64.whl (1.1MB)
     |████████████████████████████████| 1.1MB 4.9kB/s 
Collecting docopt>=0.6.2
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting pyvmomi>=6.0.0
  Downloading https://files.pythonhosted.org/packages/eb/87/ebf153a3aafdac7c54c5578b6240d7930a8c0a1a21bdd98d271fd131673c/pyvmomi-6.7.3.tar.gz (576kB)
     |████████████████████████████████| 583kB 10kB/s 
Collecting vconnector>=0.5.0
  Downloading https://files.pythonhosted.org/packages/22/9e/52cae036555ec85f0508e2d294b6bf491e496c3463784853d6f88a905662/vconnector-0.6.0.tar.gz
Collecting requests>=2.3.0
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting six>=1.7.3
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting tabulate>=0.8.3
  Downloading https://files.pythonhosted.org/packages/66/d4/977fdd5186b7cdbb7c43a7aac7c5e4e0337a84cb802e154616f3cfc84563/tabulate-0.8.5.tar.gz (45kB)
     |████████████████████████████████| 51kB 15kB/s 
Collecting idna<2.9,>=2.5
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
     |████████████████████████████████| 163kB 12kB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
     |████████████████████████████████| 133kB 3.2kB/s 
Installing collected packages: pyzmq, docopt, idna, chardet, certifi, urllib3, requests, six, pyvmomi, tabulate, vconnector, vpoller
    Running setup.py install for docopt ... done
    Running setup.py install for pyvmomi ... done
    Running setup.py install for tabulate ... done
    Running setup.py install for vconnector ... done
    Running setup.py install for vpoller ... done
Successfully installed certifi-2019.9.11 chardet-3.0.4 docopt-0.6.2 idna-2.8 pyvmomi-6.7.3 pyzmq-18.1.1 requests-2.22.0 six-1.13.0 tabulate-0.8.5 urllib3-1.25.7 vconnector-0.6.0 vpoller-0.7.3
`

**Comment by horityhu** [comment]
/etc/vpoller/vpoller.conf
I can't find the file.

**Comment by dnaeon** [comment]
The file you need to create yourself, please check the documentation for
examples.

**Comment by horityhu** [comment]
I had create the conf file,and copy the examples.
as below:
[root@zabbix4-server site-packages]# vi /etc/vpoller/vpoller.conf
[root@zabbix4-server site-packages]# mkdir /etc/vpoller
[root@zabbix4-server site-packages]# vi /etc/vpoller/vpoller.conf
[root@zabbix4-server site-packages]# sudo vconnector-cli init
`**sudo: vconnector-cli: command not found**`
[root@zabbix4-server site-packages]#

**Comment by horityhu** [comment]
I do as below:
ln -s /usr/local/python3/bin/vconnector-cli /usr/bin/
ln -s /usr/local/python3/bin/vpoller-proxy /usr/bin/
ln -s /usr/local/python3/bin/vpoller-worker /usr/bin/
ln -s /usr/local/python3/bin/vpoller-client /usr/bin/

##初始化vConnector##
1.create dir
/var/lib/vconnector/
2.init
sudo vconnector-cli init
3.create vsphere agent
sudo vconnector-cli -H 10.0.0.212 -U root -P xxxxxx add
4.enabled vsphere agent
sudo vconnector-cli -H 192.168.88.158 enable
5.show vsphere agent status
sudo vconnector-cli get

all successful.

but how to  Integration With Zabbix 4.2?

**Comment by horityhu** [comment]
【ERROR】Start worker and proxy by supervisor

`TypeError: option values must be strings
[2019-11-18 09:52:44,473 - INFO/MainProcess] Starting Worker Manager [0.7.3 release]
Traceback (most recent call last):
  File "/usr/bin/vpoller-worker", line 138, in <module>
    main()
  File "/usr/bin/vpoller-worker", line 130, in main
    concurrency=args['--concurrency']
  File "/usr/bin/vpoller-worker", line 62, in start
    manager.start()
  File "/usr/local/python3/lib/python3.7/site-packages/vpoller/worker.py", line 117, in start
    self.load_config()
  File "/usr/local/python3/lib/python3.7/site-packages/vpoller/worker.py", line 156, in load_config
    parser = ConfigParser(self.config_defaults)
  File "/usr/local/python3/lib/python3.7/configparser.py", line 638, in __init__
    self._read_defaults(defaults)
  File "/usr/local/python3/lib/python3.7/configparser.py", line 1216, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/usr/local/python3/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/local/python3/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/local/python3/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
`

**Comment by dnaeon** [comment]
https://vpoller.readthedocs.io/en/latest/configuration.html
