### ISSUE TITLE
【ERROR】Start worker and proxy by supervisor

### ISSUE THREAD

**Issue by horityhu** [dnaeon/py-vpoller#270]
start worker service error as below
env: python 3.7.5

> [2019-11-18 11:00:12,100 - INFO/MainProcess] Starting Worker Manager [0.7.3 release]
> Traceback (most recent call last):
>   File "/usr/bin/vpoller-worker", line 138, in <module>
>     main()
>   File "/usr/bin/vpoller-worker", line 130, in main
>     concurrency=args['--concurrency']
>   File "/usr/bin/vpoller-worker", line 62, in start
>     manager.start()
>   File "/usr/local/python3/lib/python3.7/site-packages/vpoller/worker.py", line 117, in start
>     self.load_config()
>   File "/usr/local/python3/lib/python3.7/site-packages/vpoller/worker.py", line 156, in load_config
>     parser = ConfigParser(self.config_defaults)
>   File "/usr/local/python3/lib/python3.7/configparser.py", line 638, in __init__
>     self._read_defaults(defaults)
>   File "/usr/local/python3/lib/python3.7/configparser.py", line 1216, in _read_defaults
>     self.read_dict({self.default_section: defaults})
>   File "/usr/local/python3/lib/python3.7/configparser.py", line 753, in read_dict
>     self.set(section, key, value)
>   File "/usr/local/python3/lib/python3.7/configparser.py", line 1197, in set
>     self._validate_value_types(option=option, value=value)
>   File "/usr/local/python3/lib/python3.7/configparser.py", line 1182, in _validate_value_types
>     raise TypeError("option values must be strings")
> TypeError: option values must be strings

**Comment by rapgro** [comment]
https://vpoller.readthedocs.io/en/latest/configuration.html
