### ISSUE TITLE
Snapshot create time

### ISSUE THREAD

**Issue by bench81** [dnaeon/py-vpoller#272]
Hello.
I managed to receive data about snapshot with vm.snapshot.get... but how can i get last snapshot createtime into item of host in zabbix? I need just a parameter last time of snapshot creation so that i can add a trigger if is older than 30 days to receive an alarm...
Is there any documentation anywhere about this?
TNX. B.R.

**Comment by dnaeon** [comment]
Snapshots have been added since a long time.

https://github.com/dnaeon/py-vpoller/issues/200
