### ISSUE TITLE
vPoller Worker - store messages in a Queue?

### ISSUE THREAD

**Issue by dnaeon** [dnaeon/py-vpoller#47]
This might be useful to provide more visiblity on what's happening on the vPoller Worker side - for reporting and monitoring purposes mainly of the vPoller Workers.

Keep in mind that ZeroMQ does not provide such functionality out of the box, so if we need one we need to develop one.

* https://docs.python.org/2/library/queue.html

**Comment by bicofino** [comment]
Maybe redis?

**Comment by dnaeon** [comment]
vPoller has been designed to use ZeroMQ, so rewriting everything with Redis support is probably not the way to go... at least not in the near future.
