### ISSUE TITLE
zabbix-vsphere-import: Also group datastores into the cluster host group

### ISSUE THREAD

**Issue by jdcraymond** [dnaeon/py-vpoller#48]
After recently setting up Zabbix and vPoller and comparing the vsphere import vs LLD functions, I really the import as it groups the hosts into host groups of the cluster.  Is there a possibility to do this with the datastores as well.  That way you can see all datastores and hosts in one group?

**Comment by dnaeon** [comment]
Closing this one as I don't have enough bandwidth to work on it. If anyone is willing to pick this up, please feel free to do so.
