### ISSUE TITLE
All agents become not reachable when vcenter is down

### ISSUE THREAD

**Issue by blackcobra1973** [dnaeon/py-vpoller#91]
Hello Marin,

An old issue is back if you use the vpoller zabbix module, and vcenter is down the queue is filled up and so all agent based monitoring becomes not reachable.  

The queue becomes empty as soon as vcenter is back online and the worker process is restarted.  

Can you have a look at it ?  

Thanks in advance, 

Kurt

**Comment by dnaeon** [comment]
Kurt,

Can you please test things out with the latest release of vPoller and vConnector and see how they perform? 

Thanks,
Marin
