### ISSUE TITLE
Is it possible to embed information returned by vpoller onto dynamic label?

### ISSUE THREAD

**Issue by frank-huang** [dnaeon/py-vpoller#96]
Hi Marin:
 I apologize if this has been covered.
 Is it possible to embed information returned by vpoller onto a dynamic label?
 I have no trouble to create dynamic label on a regular host.
 Thanks.

   Frank Huang

**Comment by dnaeon** [comment]
Closing this one as I don't have enough bandwidth to work on it. If anyone is willing to pick this up, please feel free to do so.
